### ISSUE TITLE
10.glsl/16.vertexbuffer_attributes crash on nvidia cpu / ubuntu

### ISSUE THREAD

**Issue by ch-nry** [umlaeute/Gem#103]
using latest git, on ubuntu 14.04, nvidia 620M, the example 10.glsl/16.vertexbuffer_attributes crash on window creation.
using the same computer but switching to intel 4000 GPU, the patch did not crash (and render something).

**Comment by avilleret** [comment]
according to the [backtrace](https://gist.github.com/avilleret/ecfb292a281f39700dac), the issue comes from Nvidia driver.

Note the driver version : 349.16 could be nice to have other backtrace with older driver (just to see for how long the issue is at the same place)

**Comment by avilleret** [comment]
it seems that nvidia's glGetAttribLocation doesn't like NULL pointer, 
@ch-nry could you try again with https://github.com/avilleret/Gem/commit/760561bdb49554448c99321e7dde15ba7b0beb26 ?
(also check if I didn't break things on Intel's side)

**Comment by ch-nry** [comment]
it works now with your change. (both intel and nvidia)
thanks a lot.

on both intel and nvidia, result is a bit different. and none is what i would expect from the brick shader. i think it's the quad that is triangulate in both case in diferent way. and the brick shader did not like this triangle.
i'm wondering if this example was working "correctly", or if it always behave like this.
