### ISSUE TITLE
cputype does not match previous archive members cputype (all members must match)

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#106]
hello. I just tried compiling Gem and received an error I have never seen before:

osx 10.10.5
32bit compile attempt

    Making all in Gem
    /bin/sh ../../libtool  --tag=CXX   --mode=link g++ -DPD -I/Applications/Pd.app/Contents/Resources/src  -arch i386   -g -O2 -Os -falign-loops -falign-functions -falign-jumps -funroll-loops -ffast-math -mmmx -fpascal-strings -arch i386  -o libGem.la  libGem_la-glew.lo libGem_la-Cache.lo libGem_la-ContextData.lo libGem_la-Dylib.lo libGem_la-Event.lo libGem_la-Exception.lo libGem_la-Files.lo libGem_la-GLStack.lo libGem_la-Image.lo libGem_la-ImageLoad.lo libGem_la-ImageSave.lo libGem_la-PixConvertAltivec.lo libGem_la-PixConvertSSE2.lo libGem_la-Loaders.lo libGem_la-Manager.lo libGem_la-PBuffer.lo libGem_la-Properties.lo libGem_la-Rectangle.lo libGem_la-Settings.lo libGem_la-Setup.lo libGem_la-State.lo libGem_la-VertexBuffer.lo -L/Applications/Pd.app/Contents/Resources/bin   -ldl -lz -lm
    libtool: link: rm -fr  .libs/libGem.a
    libtool: link: ar cru .libs/libGem.a .libs/libGem_la-glew.o .libs/libGem_la-Cache.o .libs/libGem_la-ContextData.o .libs/libGem_la-Dylib.o .libs/libGem_la-Event.o .libs/libGem_la-Exception.o .libs/libGem_la-Files.o .libs/libGem_la-GLStack.o .libs/libGem_la-Image.o .libs/libGem_la-ImageLoad.o .libs/libGem_la-ImageSave.o .libs/libGem_la-PixConvertAltivec.o .libs/libGem_la-PixConvertSSE2.o .libs/libGem_la-Loaders.o .libs/libGem_la-Manager.o .libs/libGem_la-PBuffer.o .libs/libGem_la-Properties.o .libs/libGem_la-Rectangle.o .libs/libGem_la-Settings.o .libs/libGem_la-Setup.o .libs/libGem_la-State.o .libs/libGem_la-VertexBuffer.o
    /Library/Developer/CommandLineTools/usr/bin/ranlib: archive member: .libs/libGem.a(libGem_la-Rectangle.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
    libtool: link: ranlib .libs/libGem.a
    /Library/Developer/CommandLineTools/usr/bin/ranlib: archive member: .libs/libGem.a(libGem_la-Rectangle.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
    /Library/Developer/CommandLineTools/usr/bin/ranlib: for architecture: i386 file: .libs/libGem.a(libGem_la-PixConvertAltivec.o) has no symbols
    make[3]: *** [libGem.la] Error 1
    make[2]: *** [all-recursive] Error 1
    make[1]: *** [all] Error 2
    make: *** [all-recursive] Error 1

**Comment by umlaeute** [comment]
it seems that you have compiled some objects as `64bit`.

most likely this is from a previous (non-32bit) built-attempt.

afaik, if you switch architectures you **must** run `make clean` before re-running `make`.

**Comment by umlaeute** [comment]
btw, Gem is regularily built for [`OSX/32bit`](https://travis-ci.org/umlaeute/Gem), so I'm pretty confident that there is no intrinsic problem here.

**Comment by megrimm** [comment]
oh duh... make clean
apologies for noise

m

On Sat, Oct 10, 2015 at 5:04 PM, umläute <notifications@github.com> wrote:

> btw, Gem is regularily built for OSX/32bit
> <https://travis-ci.org/umlaeute/Gem>, so I'm pretty confident that there
> is no intrinsic problem here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umlaeute/Gem/issues/106#issuecomment-147125697>.
>



-- 
____________________
m.e.grimm, m.f.a, ed.m.
syracuse u., tc3
megrimm.net
____________________
