### ISSUE TITLE
VLC - undefined symbol: libvlc_media_add_option

### ISSUE THREAD

**Issue by tom4tom** [umlaeute/Gem#108]
Hi,

I'm on Ubuntu 14.04 - latest GEM Git 
$ ./configure --with-libvlc-CFLAGS="-I/usr/include/vlc/" --with-libvlc-LIBS="-L/usr/lib"

Get an dlerror:
pattern : /usr/local/lib/pd/extra/Gem/gem_video*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoDC1394.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoDV4L.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoUNICAP.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoV4L.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoV4L2.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoVLC.so'!
library loading returned: dlerror '/usr/local/lib/pd/extra/Gem/gem_videoVLC.so: undefined symbol: libvlc_media_add_option'

Any Help?

Cheers, ToM

**Comment by umlaeute** [comment]
which libvlc version is this?

**Comment by umlaeute** [comment]
it seems that your `libvlc-LIBS` argument is missing the actual `-lvlc`.

in general, you should do something like

     ./configure \
           --with-libvlc-CFLAGS="$(pkg-config --cflags libvlc)" \
           --with-libvlc-LIBS="$(pkg-config --libs libvlc)"

**Comment by tom4tom** [comment]
Thx IOhannes, this rocks ;-)

I use VLC 2.2.1: http://ppa.launchpad.net/mc3man/trusty-media/ubuntu
