### ISSUE TITLE
UVW mapping not working

### ISSUE THREAD

**Issue by hellocatfood** [umlaeute/Gem#112]
I've exported several models from Blender that have UVW mapping coordinates set but when I then load this into Pure Data any textures applied don't look right. I've attached an example patch to illustrate. On the left is an imported cube from Blender and on the right a [cube] object, both textured with the same image.
[uvw.zip](https://github.com/umlaeute/Gem/files/257120/uvw.zip)

**Comment by sepppirch** [comment]
same for me. old [model] wich used to work on win and linux since 0.42 show wrong textures.

**Comment by umlaeute** [comment]
fixed with 78f3f32540a00c96df80bf08ab495dd63b1a6dd4
