### ISSUE TITLE
gemvertexbuffer on windows

### ISSUE THREAD

**Issue by XRoemer** [umlaeute/Gem#114]
Hi,

I try to draw a waveform with GEM. Therefore it would be handy, to be able to draw vertices.

I downloaded GEM 0.93.3 for Windows. It works, but it seems, that the vertex buffer is disabled. I downloaded also gemvertexbuffer-help.pd from your source and pd tells me, that it can't create [gemvertexbuffer].

1. Is there a way to enable it?

2. I would like to draw a waveform while it gets recorded. It's possible in pd, but it takes 90% of my cpu and it's also only drawn in milliseconds, not in herz. Here you'll find an example:
[https://github.com/XRoemer/Diverse/blob/master/actualizing_scope_with_pd.pd]
Choose a sample in the loop player, start it, set the toggle button on the right to true and take a look at the table graph.

Would it be possible to do it with GEM while keeping cpu usage low? 

Regards,
Xaver

**Comment by umlaeute** [comment]
please do not ask multiple questions in a single ticket.

ad 1: `[gemvertexbuffer]` has only been added toGem-0.94; to *enable* it, you simply need a newer version of Gem (unfortunately 0.94 hasn't been released yet).

**Comment by XRoemer** [comment]
I tried to compile Gem on win7 myself but it failes already in the beginning. I'm unexperienced  with compiling, so I need some help. 

I didn't want to open another issue, as I saw, that an issue on building on windows and MinGW already exists. #32  I don't know, if this is related.

My specs are: win7, nvidia 560ti, and the recent versions of pd-vanilla, gem and MinGW. They are on my harddrive as c:/pd, c:/MinGW and c:/Gem. pd, Gem and MinGW are in my windows PATH variable

I tried to follow the wiki:
https://github.com/umlaeute/Gem/wiki/How-to-build-Gem-on-Microsoft-Windows-(MINGW)

I didn't install any third party libraries.

I didn't fully understand how to remap the paths in the fstab file, but as they are under C, I did <cd C:/Gem> in msys.bat to change into the Gem folder. Than I ran <./autogen.sh>

This is the output:

Homer@Homer-PC /c/gem
$ ./autogen.sh
PATH: .:/usr/local/bin:/mingw/bin:/bin:/c/ProgramData/Oracle/Java/javapath:/c/Program Files (x86)/NVIDIA Corpo
ration/PhysX/Common:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerSh
ell/v1.0/:/c/Program Files (x86)/Git/cmd:/c/Program Files (x86)/Mozilla Firefox:/c/Program Files (x86)/Inkscap
e/:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/:/c/Program Files/Microsoft SQL Server/
110/Tools/Binn/:/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0/:/c/Program Files/Microsoft SQL Server/12
0/Tools/Binn/:/h/Programmierung/Eclipse_Workspace/sharedlibrary:/c/Python34:/c/Program Files (x86)/Skype/Phone
/:/c/Windows/system32/config/systemprofile/.dnx/bin:/c/Program Files/Microsoft DNX/Dnvm/:/c/Program Files (x86
)/LilyPond/usr/bin/:/c/Pd/:/c/Windows/System32:/c/Gem:/h/texlive/2014/bin/win32:/c/Program Files (x86)/Inkscap
e/inkscape.exe:/c/Program Files/Sublime Text 3:/c/Program Files/Sublime Text 3/tidy:/c/MinGW/bin/:/c/Program F
iles (x86)/LilyPond/usr/bin/lilypond.exe:/c/Pd:.
AUTORECONF:
AUTOHEADER: /bin/autoheader
AUTOMAKE  : /bin/automake
ACLOCAL   : /bin/aclocal
LIBTOOL   : /c/MinGW/bin/libtool
LIBTOOLIZE: /c/MinGW/bin/libtoolize
AUTOCONF  : /bin/autoconf
not running autoreconf...falling back to
faking autoreconf..
/c/gem /c/gem
/c/gem
faking autoreconf for /c/gem/.
/c/gem /c/gem
  /bin/aclocal -I . -I /c/gem/m4
  /c/MinGW/bin/libtoolize --automake -c
libtoolize: $pkgltdldir is not a directory: `/mingw/share/libtool'

**Comment by avilleret** [comment]
hi @XRoemer, 

you may have a look at https://github.com/umlaeute/Gem/wiki/How-to-build-Gem-on-Microsoft-Windows
Visual Studio is freely available and you may have more success to build Gem under Visual Studio.
But it may be easier to install a linux based system to build and run Gem :-)

**Comment by XRoemer** [comment]
I do have different distributions of linux systems on vbox. I'll try to cross compile first using:
https://github.com/umlaeute/Gem/wiki/How-to-build-Gem-on-Linux-for-Windows

I need a windows version, as I use an older soundcard from terratec, which has quite good a/d converters and still works well, but I couldn't find any linux drivers for that card.

**Comment by XRoemer** [comment]
I tried to compile Gem for Windows on Ubuntu 15.04 and 16.04 (VBox).
Both failed after $ make. Both had the same errors.
I didn't install any plugins.

While building autogen.sh, I receive a message, that imake crashed. But I could go on.

These are the commands I used for $ ./configure
./configure --host=i686-w64-mingw32 --without-All --with-pd=${HOME}/lib/W32/pd --with-vfw32 --without-ftgl

configure finished without any errors

make finishes with errors. This is my output:
`xgr@xgr-VirtualBox:~/src/puredata/externals/Gem$ make
Making all in src
make[1]: Verzeichnis „/home/xgr/src/puredata/externals/Gem/src“ wird betreten
make  all-recursive
make[2]: Verzeichnis „/home/xgr/src/puredata/externals/Gem/src“ wird betreten
Making all in Gem
make[3]: Verzeichnis „/home/xgr/src/puredata/externals/Gem/src/Gem“ wird betreten
/bin/bash ../../libtool  --tag=CC   --mode=compile i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../../src  -I../../src -DGEM_INTERNAL  -DGLEW_BUILD -DGLEW_MX  -DPD -I/home/xgr/lib/W32/pd/src   -g -O2 -MT libGem_la-glew.lo -MD -MP -MF .deps/libGem_la-glew.Tpo -c -o libGem_la-glew.lo `test -f 'glew.c' || echo './'`glew.c
libtool: compile:  i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../../src -I../../src -DGEM_INTERNAL -DGLEW_BUILD -DGLEW_MX -DPD -I/home/xgr/lib/W32/pd/src -g -O2 -MT libGem_la-glew.lo -MD -MP -MF .deps/libGem_la-glew.Tpo -c glew.c  -DDLL_EXPORT -DPIC -o .libs/libGem_la-glew.o
libtool: compile:  i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../../src -I../../src -DGEM_INTERNAL -DGLEW_BUILD -DGLEW_MX -DPD -I/home/xgr/lib/W32/pd/src -g -O2 -MT libGem_la-glew.lo -MD -MP -MF .deps/libGem_la-glew.Tpo -c glew.c -o libGem_la-glew.o >/dev/null 2>&1
mv -f .deps/libGem_la-glew.Tpo .deps/libGem_la-glew.Plo
/bin/bash ../../libtool  --tag=CXX   --mode=compile i686-w64-mingw32-g++ -DHAVE_CONFIG_H -I. -I../../src  -I../../src -DGEM_INTERNAL  -DGLEW_BUILD -DGLEW_MX  -DPD -I/home/xgr/lib/W32/pd/src   -g -O2 -freg-struct-return -mms-bitfields -O3 -falign-loops -falign-functions -falign-jumps -funroll-loops -ffast-math -mmmx -MT libGem_la-Cache.lo -MD -MP -MF .deps/libGem_la-Cache.Tpo -c -o libGem_la-Cache.lo `test -f 'Cache.cpp' || echo './'`Cache.cpp
libtool: compile:  i686-w64-mingw32-g++ -DHAVE_CONFIG_H -I. -I../../src -I../../src -DGEM_INTERNAL -DGLEW_BUILD -DGLEW_MX -DPD -I/home/xgr/lib/W32/pd/src -g -O2 -freg-struct-return -mms-bitfields -O3 -falign-loops -falign-functions -falign-jumps -funroll-loops -ffast-math -mmmx -MT libGem_la-Cache.lo -MD -MP -MF .deps/libGem_la-Cache.Tpo -c Cache.cpp  -DDLL_EXPORT -DPIC -o .libs/libGem_la-Cache.o
libtool: compile:  i686-w64-mingw32-g++ -DHAVE_CONFIG_H -I. -I../../src -I../../src -DGEM_INTERNAL -DGLEW_BUILD -DGLEW_MX -DPD -I/home/xgr/lib/W32/pd/src -g -O2 -freg-struct-return -mms-bitfields -O3 -falign-loops -falign-functions -falign-jumps -funroll-loops -ffast-math -mmmx -MT libGem_la-Cache.lo -MD -MP -MF .deps/libGem_la-Cache.Tpo -c Cache.cpp -o libGem_la-Cache.o >/dev/null 2>&1
mv -f .deps/libGem_la-Cache.Tpo .deps/libGem_la-Cache.Plo
/bin/bash ../../libtool  --tag=CXX   --mode=compile i686-w64-mingw32-g++ -DHAVE_CONFIG_H -I. -I../../src  -I../../src -DGEM_INTERNAL  -DGLEW_BUILD -DGLEW_MX  -DPD -I/home/xgr/lib/W32/pd/src   -g -O2 -freg-struct-return -mms-bitfields -O3 -falign-loops -falign-functions -falign-jumps -funroll-loops -ffast-math -mmmx -MT libGem_la-ContextData.lo -MD -MP -MF .deps/libGem_la-ContextData.Tpo -c -o libGem_la-ContextData.lo `test -f 'ContextData.cpp' || echo './'`ContextData.cpp
libtool: compile:  i686-w64-mingw32-g++ -DHAVE_CONFIG_H -I. -I../../src -I../../src -DGEM_INTERNAL -DGLEW_BUILD -DGLEW_MX -DPD -I/home/xgr/lib/W32/pd/src -g -O2 -freg-struct-return -mms-bitfields -O3 -falign-loops -falign-functions -falign-jumps -funroll-loops -ffast-math -mmmx -MT libGem_la-ContextData.lo -MD -MP -MF .deps/libGem_la-ContextData.Tpo -c ContextData.cpp  -DDLL_EXPORT -DPIC -o .libs/libGem_la-ContextData.o
libtool: compile:  i686-w64-mingw32-g++ -DHAVE_CONFIG_H -I. -I../../src -I../../src -DGEM_INTERNAL -DGLEW_BUILD -DGLEW_MX -DPD -I/home/xgr/lib/W32/pd/src -g -O2 -freg-struct-return -mms-bitfields -O3 -falign-loops -falign-functions -falign-jumps -funroll-loops -ffast-math -mmmx -MT libGem_la-ContextData.lo -MD -MP -MF .deps/libGem_la-ContextData.Tpo -c ContextData.cpp -o libGem_la-ContextData.o >/dev/null 2>&1
mv -f .deps/libGem_la-ContextData.Tpo .deps/libGem_la-ContextData.Plo
/bin/bash ../../libtool  --tag=CXX   --mode=compile i686-w64-mingw32-g++ -DHAVE_CONFIG_H -I. -I../../src  -I../../src -DGEM_INTERNAL  -DGLEW_BUILD -DGLEW_MX  -DPD -I/home/xgr/lib/W32/pd/src   -g -O2 -freg-struct-return -mms-bitfields -O3 -falign-loops -falign-functions -falign-jumps -funroll-loops -ffast-math -mmmx -MT libGem_la-Dylib.lo -MD -MP -MF .deps/libGem_la-Dylib.Tpo -c -o libGem_la-Dylib.lo `test -f 'Dylib.cpp' || echo './'`Dylib.cpp
libtool: compile:  i686-w64-mingw32-g++ -DHAVE_CONFIG_H -I. -I../../src -I../../src -DGEM_INTERNAL -DGLEW_BUILD -DGLEW_MX -DPD -I/home/xgr/lib/W32/pd/src -g -O2 -freg-struct-return -mms-bitfields -O3 -falign-loops -falign-functions -falign-jumps -funroll-loops -ffast-math -mmmx -MT libGem_la-Dylib.lo -MD -MP -MF .deps/libGem_la-Dylib.Tpo -c Dylib.cpp  -DDLL_EXPORT -DPIC -o .libs/libGem_la-Dylib.o
Dylib.cpp: In static member function ‘static GemDylibHandle* GemDylibHandle::open(std::__cxx11::string)’:
Dylib.cpp:114:35: error: ‘buf’ was not declared in this scope
     handle->w32handle=LoadLibrary(buf);
                                   ^
Makefile:741: die Regel für Ziel „libGem_la-Dylib.lo“ scheiterte
make[3]: *** [libGem_la-Dylib.lo] Fehler 1
make[3]: Verzeichnis „/home/xgr/src/puredata/externals/Gem/src/Gem“ wird verlassen
Makefile:766: die Regel für Ziel „all-recursive“ scheiterte
make[2]: *** [all-recursive] Fehler 1
make[2]: Verzeichnis „/home/xgr/src/puredata/externals/Gem/src“ wird verlassen
Makefile:630: die Regel für Ziel „all“ scheiterte
make[1]: *** [all] Fehler 2
make[1]: Verzeichnis „/home/xgr/src/puredata/externals/Gem/src“ wird verlassen
Makefile:660: die Regel für Ziel „all-recursive“ scheiterte
make: *** [all-recursive] Fehler 1`

Are there any suggestions what to do?
Regards,
Xaver

**Comment by umlaeute** [comment]
please file a separate issue about *this* compilation problem.

**Comment by umlaeute** [comment]
well, it should be fixed with 16696d9

**Comment by XRoemer** [comment]
Compiling works now.
Thanks!
