### ISSUE TITLE
text2d dissapear if you move it too far

### ISSUE THREAD

**Issue by kubriel** [umlaeute/Gem#116]
if you move text2d outside of window area(for 4:3 it is -5.33 5.33 for axis x, -4 4 for axis y), it will dissapear.
if line is longer than the screen, you cannot really move it around.

steps to reproduce:
not visible:
[gemhead]
[translateXYZ 0 4.1 0]
[text2d]

visible:
[gemhead]
[translateXYZ 0 3.9 0]
[text2d]

**Comment by umlaeute** [comment]
this is a side-effect of pixmap/bitmap fonts.

nothing we can do about (apart from properly documenting it)
