### ISSUE TITLE
multimodel not draw

### ISSUE THREAD

**Issue by r33p** [umlaeute/Gem#118]
[multimodel] load the *.obj files : 

[multimodel]: loaded models: /data/Projets/2015_VJSet/002.3d.Marcheur/persos_mvt_all/perso_0 .obj from 0 to 10 skipping 1

But nothing is draw in the gemwindow.
Is this related to : 
https://github.com/umlaeute/Gem/issues/31
?

GEM 0.93.git 54b4b7c
Pd 0.46.2
Debian 8.5

$ uname -a
Linux reep 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

**Comment by umlaeute** [comment]
it's only indirectly related to #31 : the fix for the multi-render context involved some major code refactoring and `[multimodel]` simply hasn't caught up yet...

**Comment by umlaeute** [comment]
fixed with d73a166d780de4fd9fc364350a9a0634af27d74f
