### ISSUE TITLE
how to switch between model loader backends ?

### ISSUE THREAD

**Issue by avilleret** [umlaeute/Gem#122]
Hi,

at some point, gem_modelASSIMP3 seems to be lots slower than gem_modelOBJ at displaying OBJ model.
Since I have the two on my system and want to keep both, I would like to know how is it possible to dynamically switch between different model loader backends ?
I mean like the [driver int( message of [pix_video].

(I'm on Ubuntu 16.04.1)

**Comment by umlaeute** [comment]
could you provide a test-model that exhibits the slow rendering of `modelASSIMP3`?

(i agree with everything and #123, but still - i'd like ASSIMP3 to be on par with OBJ performance wise)

**Comment by avilleret** [comment]
Here is a patch and a model that demonstrates the issue.
Note also that the model doesn't look the same with the two backend.
To use the `[backend (` message, please checkout https://github.com/avilleret/Gem/tree/feature/model_backendsMess (or my dev branch)
[model-test-assimp3.zip](https://github.com/umlaeute/Gem/files/580459/model-test-assimp3.zip)

**Comment by umlaeute** [comment]
for what it is worth, i think i've fixed both the appearance and the performance of the `modelASSIMP3` to be identical with `modelOBJ` (commit 794d1255...6895334)
