### ISSUE TITLE
things behind the window shows up in transparent object with solid background

### ISSUE THREAD

**Issue by avilleret** [umlaeute/Gem#124]
I just realize there is one big caveat in #119 when you draw something transparent in a window with alpha channel and solid background.
Everything behind the window will appear through object transparency.
I see the same result in this small test program : 
[test-program.tar.gz](https://github.com/umlaeute/Gem/files/589722/test-program.tar.gz) (adapted from: https://github.com/datenwolf/codesamples/blob/master/samples/OpenGL/x11argb_opengl/x11argb_opengl.c)

Here is a patcher that demonstrates the issue : 
[test-transparent_background-bug.zip](https://github.com/umlaeute/Gem/files/589726/test-transparent_background-bug.zip)

I don't think this is a bug but a side-effect of window with alpha channel.
So I'm sure we need to make a window without alpha channel by default to avoid that. (but maybe I'm wrong)

**Comment by umlaeute** [comment]
do you mean the effect shown in the attachment?
(this has a background color of `1 1 1 1`, and two additional `square`s behind the `cube`
![transparent](https://cloud.githubusercontent.com/assets/214034/20286285/4b1fc59e-aac6-11e6-9258-9f265938eae7.png).

(at least firefox doesn't render the transparency, so you might need to look at the image gimp or the like...)

**Comment by avilleret** [comment]
not exactly.
I mean that : 
![image](https://cloud.githubusercontent.com/assets/504914/20298671/6ac493ce-ab17-11e6-8579-a3a29d833eb0.png)
.
We can see the terminal output in the red cube which is annoying since the background is solid blue.
We may find an alpha mode that works but at least the default one will break backward compatibility.

If I put a square behind the cube, I can still see the terminal behind the window : 
![image](https://cloud.githubusercontent.com/assets/504914/20298765/04d1df30-ab18-11e6-9602-792de5310e79.png)

**Comment by umlaeute** [comment]
while i don't see that (i didn'tsee the transparent glxwindow, but this is related to the used compositor; normally i'm using xfce4 with the compositor disabled; if i switch the compositor on, i have the same effect).

anyhow, i think that the png i uploaded above, exhibits this very problem (background being non-transparent; but whereever it is hidden by the semi-opaque cube, it becomes transparent)

**Comment by avilleret** [comment]
according to : http://stackoverflow.com/questions/35245809/qt-opengl-translucent-objects-show-content-from-behind-window this is related to the blending function.
But I can't find a blending mode to reproduce the behavior of a non transparent window with a transparent one. 
So we need to make transparent window an option.

**Comment by avilleret** [comment]
according to [datenwolf's answer](http://stackoverflow.com/a/40677580/3203032) we need to implement separable blend function to solve this.
To do so, we need glBlendFunci which was introduce with OpenGL 4.0.
I will try to have a look into that later.

**Comment by umlaeute** [comment]
since #126 has been merged, i'm closing this, as it seems to have been fixed.
