### ISSUE TITLE
couldn't find [gemglutwindow] for window#1, window#2, etc on OSX

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#136]
osx 10.12
macbook pro

each time a new window is created and then destroyed the following error occurs:

`couldn't find [gemglutwindow] for window#1`

when repeated the window # given increases by one so:

`couldn't find [gemglutwindow] for window#2`
`couldn't find [gemglutwindow] for window#3`
`couldn't find [gemglutwindow] for window#4`

also getting many errors:
GL: invalid framebuffer operation
GL: invalid operation

I am also noticing TONS of depreciation warnings when compiling both [gemcocoawindow] and [gemglutwindow] when compiling. I can post these if needed.

**Comment by umlaeute** [comment]
it seems that the glut still sends messages from the window, after Gem thinks that the window no longer exists.
