### ISSUE TITLE
'magick/MagickCore.h' file not found OSX 10.12 Macbook Pro

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#142]
Back to Gem compile on OSX I was trying to track some of these ImageMagick errors down again but now I am getting: 

`MagickCore.cpp:36:10: fatal error: 'magick/MagickCore.h' file not found`

I am honestly not sure what changed on my system since the last time I gave Gem compile a whirl but I am assuming its me...? ImageMagick and Graphicsmagick are both installed and system linked via homebrew.

Anyway, during configure:
```
checking for PKG_IMAGEMAGICK__... yes
checking for main in -lMagick++... (cached) yes
checking Magick++.h usability... no
checking Magick++.h presence... no
checking for Magick++.h... no
checking for PKG_MAGICKCORE... yes
checking for IsMagickInstantiated in -lMagick... (cached) yes
checking magick/MagickCore.h usability... no
checking magick/MagickCore.h presence... no
checking for magick/MagickCore.h... no
```

Durring compile:
```
In file included from MagickCore.cpp:19:
In file included from ./imageMAGICK.h:17:
../../src/plugins/imagesaver.h:71:97: warning: '/*' within block comment [-Wcomment]
       *                                     even though we only expect mimetypes of type 'image/*', the prefix ('image/') is mandatory
                                                                                                ^
MagickCore.cpp:36:10: fatal error: 'magick/MagickCore.h' file not found
#include <magick/MagickCore.h>
         ^
1 warning and 1 error generated.
make[2]: *** [gem_imageMAGICK_la-MagickCore.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

I do notice MagickCore.h is system linked @ /usr/local/include/ImageMagick-7/MagickCore/ so I am not sure how MagickCore.h is found if looking for magick/MagickCore.h

**Comment by umlaeute** [comment]
what's the output of

    pkg-config --cflags MagickCore

**Comment by megrimm** [comment]
`-DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.0.5-4/include/ImageMagick-7`

**Comment by umlaeute** [comment]
thanks. and the exact content of `/usr/local/Cellar/imagemagick/7.0.5-4/include/ImageMagick-7`?

    ls -l /usr/local/Cellar/imagemagick/7.0.5-4/include/ImageMagick-7

**Comment by megrimm** [comment]
```
total 8
drwxr-xr-x  17 megrimm  admin   578 Apr 24 21:19 Magick++
-rw-r--r--   1 megrimm  admin   713 Apr 24 21:19 Magick++.h
drwxr-xr-x  97 megrimm  admin  3298 Apr 24 21:19 MagickCore
drwxr-xr-x  25 megrimm  admin   850 Apr 24 21:19 MagickWand
```

**Comment by umlaeute** [comment]
i see.

IM-7 [changed their header-locations](https://www.imagemagick.org/script/porting.php#headers) from `magick/` to `MagickCore/`.

this obviously needs adoption on the Gem-side
