### ISSUE TITLE
Setup.cpp:189:5: error: OSX 10.12.5 Pd-0.48-0-test1

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#147]
Compiling against new test Pd-0.48-0-test1 on OSX 10.12.5 using wiki instructions (https://github.com/umlaeute/Gem/wiki/How-to-build-Gem-on-macOS-Sierra-(10.12)) I get error that I have seen for first time:

clang: warning: optimization flag '-falign-loops' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-falign-functions' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-falign-jumps' is not supported [-Wignored-optimization-argument]
Setup.cpp:189:5: error: use of undeclared identifier 'sys_searchpath'
    sys_searchpath = namelist_append(sys_searchpath, mypath, 0);
    ^
Setup.cpp:189:38: error: use of undeclared identifier 'sys_searchpath'
    sys_searchpath = namelist_append(sys_searchpath, mypath, 0);
                                     ^
2 errors generated.
make[3]: *** [libGem_la-Setup.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by umlaeute** [comment]
afaict, this has been fixed with pure-data/pure-data@c34380ab1ea598068c7e293322b87e7c3a05bfe2 (and thus in the upcoming *Pd-0.48-0-test2*)

**Comment by umlaeute** [comment]
pure-data/pure-data@c34380a only fixed ABI compatibility, but not API compatibility, so the build still fails.

**Comment by megrimm** [comment]
i just compiled with your recent changes to Setup.cpp and all seems to compile fine. so this is resolved no?

**Comment by umlaeute** [comment]
kind of; but i would like to submit an even better solution to the problem...
