### ISSUE TITLE
compiling Gem on Mac OS X fails - configure: error: GL (headers) not found!

### ISSUE THREAD

**Issue by popesz** [umlaeute/Gem#153]
I want to compile Gem from github on Mac OS X but already at configure I got the error:

configure: error: GL (headers) not found! you need openGL!!

however
glxinfo says:

glxinfo | grep "OpenGL version"

OpenGL version string: 2.1 ATI-1.51.8

How can I compile with success?
Any hints?

Best,
Popesz

Mac OS X 10.12.6
MacBook Pro (Retina, 15-inch, Mid 2015)
Processor: 2,5 GHz Intel Core i7
Graphics: AMD Radeon R9 M370X 2048 MB
Intel Iris Pro 1536 MB
[OpenGL missing.zip](https://github.com/umlaeute/Gem/files/1284648/OpenGL.missing.zip)

**Comment by umlaeute** [comment]
please attach the logfiles as plain text files (preferably zipped). please do *not* use `doc`, `ods` or `rtf`.

**Comment by umlaeute** [comment]
Also the output of `glxinfo` is irrelevant in two aspects:
- on OSX we don't use `GLX` (which is *Open**GL** for **X**-Servers*) but the native OpenGL framework
- the success of `glxinfo` (or similar), only shows that you have the runtime libraries for OpenGL installed. It doesn't tell us anything about the presence of *Developer* headers/libraries.

Please also include the generated `config.log` file.

**Comment by popesz** [comment]
Here you are:

[config.log.zip](https://github.com/umlaeute/Gem/files/1286023/config.log.zip
Thanks for your help:
Popesz

**Comment by megrimm** [comment]
could it be possible your command line tools are not installed or not installed properly? you ran i assume:

`$ xcode-select --install`

what do these tell you:
`$ xcode-select -p`
`$ xcode-select -v`

**Comment by popesz** [comment]
Let's see:

EMVision:Gem EMV$ xcode-select -p

/Applications/Xcode.app/Contents/Developer

EMVision:Gem EMV$ xcode-select -v

xcode-select version 2347.

**Comment by megrimm** [comment]
well thats right...

hmmm... not sure if it has any relation to [https://github.com/umlaeute/Gem/issues/26](https://github.com/umlaeute/Gem/issues/26)

it also seems like you are compiling against a 32bit version of Pd?

i have attached  my log file from successful ./configure.... maybe there is something there to look for? you can do something like:

`diff -u your.config.log my.config.log | mate`

which pipes diff output to textmate if you have that installed.

also... curious... have you tried to build after configure?

[config.log.zip](https://github.com/umlaeute/Gem/files/1288875/config.log.zip)

**Comment by popesz** [comment]
tried to build but I got an error:

fatal error: 'FTFont.h' file not found


the solution from here:

https://github.com/umlaeute/Gem/issues/27 such as

make CPPFLAGS=`pkg-config --cflags freetype2`did not solve my problem. but
looks like here is the problem somewhere

**Comment by megrimm** [comment]
i remember having trouble such as this a couple years ago but I do not remember the steps I took to resolve. I do not think it is Gem (since mine has been building fine for quite a while) but likely how your system is set up. You might want to try uninstalling pkg-config, gettext, automake, libtool and then reinstall in the correct order....

i remember getting this all setup and working can be really finicky. can you uninstall homebrew stuff and follow [this](https://github.com/umlaeute/Gem/wiki/How-to-build-Gem-on-macOS-Sierra-(10.12)) closely after uninstalling homebrew stuffs?

**Comment by popesz** [comment]
Tried all your suggestions, removed the mentioned libraries, and
reinstalled it. Tried with and without ftgl, and the same opengl error
blocks the configuration.
However building goes quite far, but stops at this point:

ld: library not found for -lglfw3

checked it:

brew install glfw@3

Warning: glfw 3.2.1 is already installed

so again stucked.

**Comment by megrimm** [comment]
wow... quite the ordeal here :)

if you do:

`$ ./configure --help`

you get a bunch of command line options. you can try a bunch out just at least to get it to build correctly... then maybe we figure out what the initial error is all about.

so for example:

`$ ./configure --without-glfw3`

disables glfw3 (GLFW3 windowing).... so keep finding what is causing your hang ups, disable, and try again. process of elimination i guess... :)

**Comment by popesz** [comment]
managed to build and install for 64 bit, works fine under 0.48-0.
had to disable glfw3. Now just one quick question, how can I test if openGL
works with Gem?

Thanks for the help and patience.
Popesz

**Comment by umlaeute** [comment]
On 2017-09-11 13:52, popesz wrote:
> how can I test if openGL works with Gem?

if you can draw *anything*, then openGL works.

fgamsdr
IOhannes

**Comment by popesz** [comment]
you mean in gemwindow?
then yes, it works.
Thanks
