### ISSUE TITLE
plugin videoDecklink is missing tiny bit of documentation

### ISSUE THREAD

**Issue by kubriel** [umlaeute/Gem#155]
i was also able to capture only 720x576 with my 'DeckLink Mini Recorder 4K'.
there appears two properties in pix_video-help.pd
as i understandd one is source number and second is format number.
it is not clear what numbering plugin uses, as gstreamer, ffmpeg and bmdcapture uses different numberings.

**Comment by umlaeute** [comment]
for the source, the numbers are known (and hardcoded), though you probably want to use the symbolic descriptors instead:

~~~,
SDI = 0,
HDMI,
OpticalSDI,
Component,
Composite,
SVideo,
~~~

the format is somewhat opaque, and comes from the interface itself.

**Comment by umlaeute** [comment]
i guess the proper way to resolve this is by adding read-only `formats` and `connections` properties, that return the available options.
