### ISSUE TITLE
Win10: pix_image does not find files in folders with Umlaut

### ISSUE THREAD

**Issue by musger** [umlaeute/Gem#157]
I create a directory namend "folder" that holds a patch                                                                
        image.pd                                                                                                       
consisting of a render graph with a [pix_image rockstar.jpg] object etc.                                               
and an image file                                                                                                      
        rockstar.jpg                                                                                                   
in the same directory. It loads fine, unless the folder name is changed                                                
to contain an umlaut such as in "földer".                                                                              
                                                                                                                       
Then the following error message is posted:                                                                            
GEM: recordQT: error -50 in FSMakeFSSpec()                                                                             
GemImageLoad: Unable to find file: C:/Users/rockstar/Desktop/földer/rockstar.jpg parID : 150470656                                                                                                      
[pix_image]: loading of 'C:/Users/rockstar/Desktop/földer/quinn.jpg' failed                                            
                                                                                                                       
This is on Windows 10 Enterprise 10.0.14393

**Comment by musger** [comment]
The same might apply to filenames and paths of [pix_video] as well.

**Comment by umlaeute** [comment]
`[pix_video]` or `[pix_film]`?

**Comment by musger** [comment]
Darn, meant [pix_film] of course. Too many pix_... objects on my mind. Sorry.
