### ISSUE TITLE
pix_crop helppatch gives wrong argument order

### ISSUE THREAD

**Issue by signingUpOnlyToReport** [umlaeute/Gem#159]
The help patch for pix_crop lists the arguments as
<offX=0> <offX=0> <dimX=64> <dimX=64> 
while it should list the order as the inlets are, ie
<dimX=64> <dimX=64> <offX=0> <offX=0>

**Comment by umlaeute** [comment]
the thing is, that the arguments are indeed reversed with respect to the inlets.
- order of arguments: `x y width height`
- order of inlets: `(gemlist) width height x y`

this is inconsistent.
but fixing it, will most likely break a number of patches

**Comment by signingUpOnlyToReport** [comment]
* umläute <notifications@github.com> [2017-11-14 09:51]:
> the thing is, that the arguments are indeed reversed with respect to the inlets.
> - order of arguments: `x y width height`
> - order of inlets: `(gemlist) width height x y`
> 
> this is inconsistent.
> but fixing it, will most likely break a number of patches
Could the help patch mention this reverse order to avoid further
confusion perhaps?
