### ISSUE TITLE
pix_film loops on Windows but not on OS X or Linux

### ISSUE THREAD

**Issue by musger** [umlaeute/Gem#160]
Loading an somefile.avi file into [pix_film] on Windows10 and sending the [auto 1< message will start playback that loops when the file end is reached. Converting the same file to .mov using 
ffmpeg -i somefile.avi somefile.mov
and loading it into [pix_film] on OS X will not loop playback when sending an [auto 1< message. Playing either somefile.avi or somefile.mov on Debian Linux will not loop playback.

The help patch describes the latter behavior as being the intended behavior.
The files are attached in zipped format as github does not allow .avi nor .mov
[somefiles.zip](https://github.com/umlaeute/Gem/files/1475818/somefiles.zip)

**Comment by umlaeute** [comment]
given that this is backend-specific, we'd need to know which backend you were actually using to play back the film?

**Comment by musger** [comment]
How do I find out which backend I am using? Upon loading my videofile into pix_video Pd/Gem prints on the console:
[pix_film]: DirectShow support
[pix_film]: QuickTime support
Image loading support: QT SGI jpeg tiff
GEM: GLEW version 1.5.4
GEM: Start rendering
[pix_film]: opening C:/vid/somefile.avi with format 1908
[pix_film]: loaded file: C:/vid/somefile.avi with 464 frames (320x240) at -1.000000 fps

**Comment by musger** [comment]
How do I find out which backend I am using? Upon loading my videofile into pix_video Pd/Gem prints on the console:
[pix_film]: DirectShow support
[pix_film]: QuickTime support
Image loading support: QT SGI jpeg tiff
GEM: GLEW version 1.5.4
GEM: Start rendering
[pix_film]: opening C:/vid/somefile.avi with format 1908
[pix_film]: loaded file: C:/vid/somefile.avi with 464 frames (320x240) at -1.000000 fps

**Comment by umlaeute** [comment]
you probably have to start `pd.com` from the console and see the output to `stderr` (probably after adding a few `-v` flags).

you might be faster by just manually disabling all but one plugin before starting Pd (by simply moving the `gem_film*.dll` files out of the way (they are only found if they live in the very same directory as `Gem.dll`) and back again)
