### ISSUE TITLE
pix_film: Ambiguous rightmost outlet bangs randomly on Win10. 

### ISSUE THREAD

**Issue by musger** [umlaeute/Gem#161]
Loading somefile.avi into [pix_film] on Win10 and playing back via [auto 1< will output bangs at the right outlet before the file end is reached. The help patch decribes these as possibly being an "illegal frame" being decoded. Nevertheless playback does not stop. This makes it very hard to differentiate a bang issued when the end of the file is reached from a bang because there has been an "illegal" frame and will not allow any subsequent message logic making use of that outlet.
The file is attached in zipped format as github does not allow .avi

[somefile.zip](https://github.com/umlaeute/Gem/files/1475816/somefile.zip)

**Comment by umlaeute** [comment]
given that this is backend-specific, we'd need to know which backend you were actually using to play back the film?

**Comment by musger** [comment]
How do I find out which backend I am using? Upon loading my videofile into pix_video Pd/Gem prints on the console:
[pix_film]: DirectShow support
[pix_film]: QuickTime support
Image loading support: QT SGI jpeg tiff
GEM: GLEW version 1.5.4
GEM: Start rendering
[pix_film]: opening C:/vid/somefile.avi with format 1908
[pix_film]: loaded file: C:/vid/somefile.avi with 464 frames (320x240) at -1.000000 fps

**Comment by umlaeute** [comment]
hopefully fixed with e9a4769202e38d8c09cc57e98521dab8eb17806f...1a6d62d7e4326b2ffd2fcc738629c54b20cc9f21 (in the  DirectShow backend at last).

thanks for the video, btw
