### ISSUE TITLE
pix_image does not report that it can not play a file

### ISSUE THREAD

**Issue by signingUpOnlyToReport** [umlaeute/Gem#162]
Loading somefile.avi into [pix_image] on OS X does not report any errors in the Pd console, yet the object will be unable to play back the file.

**Comment by signingUpOnlyToReport** [comment]
[somefile.zip](https://github.com/umlaeute/Gem/files/1475829/somefile.zip)

**Comment by umlaeute** [comment]
has this been closed accidentally? if not, please add a short explanation.

**Comment by signingUpOnlyToReport** [comment]
* umläute <notifications@github.com> [2017-11-17 15:27]:
> has this been closed accidentally? if not, please add a short explanation.
I closed this accidentally. I meant to correct pix_image to pix_film
which I had mistaken. Wanted the issue to read:

pix_film does not report that it can not play a file

ading somefile.avi into [pix_film] on OS X does not report any errors
in the Pd console, yet the object will be unable to play back the file.

Can I re-open and edit that issue or do you want me to open a new one?

**Comment by signingUpOnlyToReport** [comment]
I opened a new issue (#170) with the correct title.

**Comment by umlaeute** [comment]
while haven't been much harm, in general i much prefer to just fix the ticket (that is: fix the title, rather than close it and open a new one; remove your password from a post rather than close the ticket and open a new one...).

i'm aware that you did ask about this and that i didn't answer in time.
