### ISSUE TITLE
pix_film on Windows does not allow playback to be restarted with auto message.

### ISSUE THREAD

**Issue by musger** [umlaeute/Gem#163]
Loading somefile.avi into [pix_film] on Win10 and sending the [auto 1< message will start playback. When playback is stopped with an [auto 0< message, it is not possible to restart it with [auto 1<.
Re-opening the file does not help. Explicitely setting a frame number prior to [auto 1< does not help. 
[somefile.zip](https://github.com/umlaeute/Gem/files/1475847/somefile.zip)

**Comment by umlaeute** [comment]
given that this is backend-specific, we'd need to know which backend you were actually using to play back the film?

**Comment by musger** [comment]
How do I find out which backend I am using? Upon loading my videofile into pix_video Pd/Gem prints on the console:
[pix_film]: DirectShow support
[pix_film]: QuickTime support
Image loading support: QT SGI jpeg tiff
GEM: GLEW version 1.5.4
GEM: Start rendering
[pix_film]: opening C:/vid/somefile.avi with format 1908
[pix_film]: loaded file: C:/vid/somefile.avi with 464 frames (320x240) at -1.000000 fps

**Comment by musger** [comment]
Some more observations:

Starting playback with [auto 1< and then stopping playback with [auto 0< and starting again with [auto 1< will not always start from the position where it was stopped. Sometimes it will display a black frame even. When an [auto 0< is sent then, a still frame is displayed.

Sometimes selecting frame number 1 using the right inlet and sending [auto 1< will not start playback. The rightmost outlet then bangs with the framerate.
Now selecting [auto 0< will display a still frame from the video which is not the first frame. Pressing [auto 1< again, will turn to a black screen and will let the rightmost output bang with the framerate.
This can also be oberved when a video is played to/beyond its last frame and [pix_film] is sent an [auto 1< message, playback will not restart (this is consistent with the help patch explanation) but pressing [auto 0< will display a still frame.

**Comment by umlaeute** [comment]
probably fixed with 97e46773101229cdb5f5abad306dd99274300a31
