### ISSUE TITLE
Improvement of explanation of default state in certain help patches

### ISSUE THREAD

**Issue by musger** [umlaeute/Gem#166]
The help patch could mention the default state of the following objects more clearly, as the presence of a switched-on toggle can imply this switching on is necessary due to a default state being "off". This is the case for:
pix_coloralpha
pix_grey
pix_hsc2rgb
pix_invert
pix_normalize
pix_rgb2hsv
pix_rgba
pix_yuv

**Comment by umlaeute** [comment]
pull requests welcome.
