### ISSUE TITLE
Feature request: Implement arguments for certain objects.

### ISSUE THREAD

**Issue by musger** [umlaeute/Gem#167]
The following objects could benefit from their paramteres being settable via arguments:
pix_a_2grey
pix_threshold
pix_backlight
pix_colorreduce
pix_compare
pix_contrast
pix_convert
pix_data
pix_dot
pix_flip
pix_gain
pix_halftone
pix_metaimage
pix_motionblur
pix_posterize
pix_rds
pix_zoom

**Comment by umlaeute** [comment]
pull requests welcome
