### ISSUE TITLE
Force case-sensitivity when loading Gem library in Windows.

### ISSUE THREAD

**Issue by musger** [umlaeute/Gem#168]
Gem should only load on Windows if written with uppercase G in order to make patches work across operating systems as Unixes will not load a [declare -lib gem].

**Comment by avilleret** [comment]
This is not specific to Gem, but to the way that Pd loads externals.
If `Gem` and `gem`  are not the same on Unixes, this is only because of case-sensitive file system, imho.

**Comment by musger** [comment]
* Antoine Villeret <notifications@github.com> [2017-11-19 21:11]:
> This is not specific to Gem, but to the way that Pd loads externals.
> If `Gem` and `gem`  are not the same on Unixes, this is only because of case-sensitive file system, imho.
Thank you! I was under the impression that there is some kind of wrapper
in Gem that makes "gem" load "Gem", at least this is what I understood
from a previous conversation. If this is true it might not be a Pd
issue...

**Comment by avilleret** [comment]
removing those lines should help : https://github.com/umlaeute/Gem/blob/cc0d464af7ab8f98375a24d437b10ad9f9fd9158/src/Gem/Setup.cpp#L237-L245

(sorry I can't try it now)
