### ISSUE TITLE
gemmouse does report values outside of gemwindow on OS X but not on Windows or Linux.

### ISSUE THREAD

**Issue by musger** [umlaeute/Gem#169]
[gemmouse] reports X and Y values if the mouse pointer is outside of the gem window on OS X but not on Windows or Linux. This can lead to patches having different results on different operating systems and is also not mentioned in the help patch.

**Comment by umlaeute** [comment]
this is probably a feature...

the exact behavior depends on the actual windowing subsystem used (glx, Cocoa, W32, glut, glfw2, glfw3, ...).
e.g. on Linux/glx, I get window coordinates when dragging (left-click + mouse movement), even if i leave the window.

it's easy enough to filter out unwanted coordinates (think `[moses]`)

with Gem-0.94, `[gemmouse]` is an abstraction, which can be adjusted to your personal taste and needs (and probably it should be more restrictive and filter out out-of-window coordinates).

**Comment by musger** [comment]
* umläute <notifications@github.com> [2017-11-20 14:32]:
> this is probably a feature...
which will sadly cause unpredictable behavior of patches. It should be
mentioned in the help patch™ at least.
 
> the exact behavior depends on the actual windowing subsystem used (glx, Cocoa, W32, glut, glfw2, glfw3, ...).
Is this something that Gem users can influence, chose or detect easily?

> e.g. on Linux/glx, I get window coordinates when dragging (left-click + mouse movement), even if i leave the window.
Right, me too.

> it's easy enough to filter out unwanted coordinates (think `[moses]`)
> 
> with Gem-0.94, `[gemmouse]` is an abstraction, which can be adjusted to your personal taste and needs (and probably it should be more restrictive and filter out out-of-window coordinates).
Can the gemwin dimensions be queried in a patch so that we could make
that abstraction filter out out-of-window coordinates?
