### ISSUE TITLE
filmDarwin does not report that it can not play an .avi file on OS X.

### ISSUE THREAD

**Issue by musger** [umlaeute/Gem#170]
Loading somefile.avi into [pix_film] on OS X does not report any errors in the Pd console, yet the object will be unable to play back the file. The object should throw an error message.

**Comment by umlaeute** [comment]
the new `filmAVF` works nicely. i guess it's only `filmDarwin` that has the problem.

**Comment by umlaeute** [comment]
since the `filmDarwin` backend is only there for legacy reasons (and it's not going to work with newer macOS versions anyhow), i'm closing this as "wontfix".
got for `filmAVF` instead.
