### ISSUE TITLE
videoDarwin flickers also with pix_separator buffer inbetween

### ISSUE THREAD

**Issue by musger** [umlaeute/Gem#176]
pix_video does flicker on at least OS X and Linux also when the camera's frame rate is decoupled from Gem's frame rate by inserting a pix_separator after pix_video.

**Comment by umlaeute** [comment]
i thought the issue was related to some processing `[pix_...]` objects in the chain.

*this* bug-report makes it sound as if a simple `[gemhead]->[pix_video]->[pix_texture]->[square]` chain would flicker.

please clarify.

**Comment by musger** [comment]
Thank you! This bug describes flicker when there is a simple
[gemhead] -> [pix_video] -> [pix_texture] -> [square] 
chain on OS X. It also flickers when there is a pix_separator inserted to buffer images as in
[gemhead] -> [pix_video] -> [pix_separator] -> [pix_texture] -> [square].

The other bug, which I asked about on pd-list, is about [pix_image] changing its state seeminly randomly when being feeded a video file or video camara feed without initializing its initial state explicitely. You asked if it would be a dup of https://sourceforge.net/p/pd-gem/bugs/33/ which made me try [pix_separator] in this #176 bug. However, the flickering [pix_invert] is not yet reported as separate bug as it is not yet clear to me if its related to https://sourceforge.net/p/pd-gem/bugs/61/ as well. I hope this confusing blurp helps nevertheless.

**Comment by umlaeute** [comment]
i don't really understand what this means:
>  about [pix_image] changing its state seeminly randomly when being feeded a video file or video camara feed without initializing its initial state explicitely.

how would you feed a video-file to `[pix_image]`?

**Comment by musger** [comment]
Please excuse me, I confused two objects. Above comment was meant to read:

The other bug, which I asked about on pd-list, is about [pix_invert] changing its state seeminly randomly when being feeded a video file or video camara feed without initializing its initial state explicitely. You asked if it would be a dup of https://sourceforge.net/p/pd-gem/bugs/33/ which made me try [pix_separator] in this #176 bug. However, the flickering [pix_invert] is not yet reported as separate bug as it is not yet clear to me if its related to https://sourceforge.net/p/pd-gem/bugs/61/ as well. I also remember [pix_flip] flickering (changing its state) with a [pix_video] source on OS X. Thanks!

**Comment by umlaeute** [comment]
would you mind amending the initial comment (and remove the new one)?

**Comment by umlaeute** [comment]
what exactly do you mean with the following?
> the camera's frame rate is decoupled from Gem's frame rate

does this simply indicate that you've inserted a `[pix_separator]`? or that the camera runs at a different speed from Gem? or that you are banging the gemchain with a `[metro]` out of sync with the framerate?

**Comment by musger** [comment]
The camera's frame rate was different from Gem's framerate. I inserted a [pix_separator] because I understood that it could help buffering images and hence decoupling the camera's and Gem's framerate. I might be mistaken. I was not banging the gemchain with a metro.

**Comment by umlaeute** [comment]
thx.
could you be more specific about the actual framerates of camera and Gem?

**Comment by musger** [comment]
From my memory I think the camera ran at 15fps, and Gem was at its default 20fps. Inserting the mentioned [pix_separator] and changing Gem to 15fps caused less flicker, but did not make it go away.
