### ISSUE TITLE
pix_video on OS X 10.10. reports errors "SFSetChannelDevice returned error -9408" and "could not set SG Rect" but works.

### ISSUE THREAD

**Issue by musger** [umlaeute/Gem#177]
These two errors are posted into the Pd console, but pix_video works. Could they be classified as warnings instead?
This error is reported on OS X 10.11.6 as well

**Comment by umlaeute** [comment]
well, QuickTtime reports them as errors.

in any case this has been fixed with f0db48bbea3f554ae34103485aed1fe6a4f10a70
