### ISSUE TITLE
Compiling on OSX 10.12.6

### ISSUE THREAD

**Issue by danielfilipealmeida** [umlaeute/Gem#179]
I'm trying to compile GEM for OSX 10.12.6 and I've came across a couple or problems.

It complains about freetype and quicktime.

I've tried to configure with the following:

`./configure --with-pd=/Users/daniel.almeida/Personal/pure-data/src --without-ftgl --without-libquicktime`

it ignores freetype but still tries to use quicktime.

I know QT is a problem with newer versions of OSX, since it has been removed. How can I compile without it? and will the videos be loaded without QT?

The error I get is:

```
imageQT.cpp:26:12: fatal error: 'QuickTime/QuickTime.h' file not found
#  include <QuickTime/QuickTime.h>
```

**Comment by umlaeute** [comment]
`libquicktime` is not the same as `QuickTime`.

the [Wiki](https://github.com/umlaeute/Gem/wiki/How-to-build-Gem-on-macOS-Sierra-%2810.12%29) lists the correct flags.
