### ISSUE TITLE
[gemcocoawindow] doesn't refresh

### ISSUE THREAD

**Issue by umlaeute** [umlaeute/Gem#182]
it seems that `[gemcocoawindow]` doesn't properly paint on my system, only when i move the entire window (or, when moving the mouse, the parts "touched" by the mouse are drawn as well).

observed under both *Mavericks* (with an old build from 2014) and *Sierra* (with the same build from 2014; and a fresh clone), both running as a VM (so it might be related to that; it really it looks like an `Xdamage` problem).

no problems with `[gemglutwindow]`.

can anybody (@megrimm :-)) confirm that this is a false positive?

**Comment by megrimm** [comment]
yeah this was the trouble i was having when i started looking/attempting to fix... 

so not working on Mavericks NOR Sierra?

... and i do not actually remember where i left off on this but could possibly take another look in a couple week when some time opens up.

**Comment by umlaeute** [comment]
@megrimm: for what it is worth, i have merged in the `gemmacoswindow` object from your `gemcocoawindow-fixes` branch.
however, i haven't tested it yet.

**Comment by umlaeute** [comment]
seems to work (at least on non-virtualized systems)
