### ISSUE TITLE
impossible to use uniform array for shaders

### ISSUE THREAD

**Issue by Jackovic** [umlaeute/Gem#183]
Hello,
It is not possible to pass a uniform variable as array to shaders.

For exemple, declaring in a shader :
uniform float pos_square[4];

and sending a message to [glsl_program] :
pos_square 0.2 0.4 0.6 0.7

return in Pd console :
[glsl_program]: no method for 'pos_square' (it's not uniform variable)

I tested my fragment shader with Processing and it works fine.

**Comment by fdch** [comment]
perhaps try `uniform vec4 pos_square`

**Comment by Jackovic** [comment]
I can also use a mat4, but i need to pass more than 16 values.

**Comment by claudeha** [comment]
I also needed this in the past.

I did manage to modify a local Gem to support it (hackily) but I'm not sure if I have those changes anywhere any more..

**Comment by umlaeute** [comment]
implemented with 61438c5e4c80fe74182f70553e00aa9ad9721b7f, at least for openGL>2 shaders (not for the old old legacy ARB shaders)
