### ISSUE TITLE
filmDS: frame message returns wrong frame

### ISSUE THREAD

**Issue by oliverstotz** [umlaeute/Gem#190]
hi, 

I lately came across a strange behaviour with the [pix_film] object, that only occurs on windows (tested it on OSX and LINUX as well). when sending an arbitrary non-consecutive frame number to its right inlet, the frame that is actually shown is the one BEFORE the last frame message.

i attached an example patch that demonstrates this behaviour. this is true for all codecs [pix_film] can load, (except for the mjpeg codec which displays the frames correctly !). on OSX and LINUX the tested movies files showed the correct frames.

[pix_film_frame_bug.zip](https://github.com/umlaeute/Gem/files/1984385/pix_film_frame_bug.zip)

**Comment by umlaeute** [comment]
most likely a bug in one of the decoder plugins (`filmQT` or `filmDS`).

to triage the problem, try disabling the plugin binaries (`gem_film*.dll`) by moving them out of the directory, and enable them selectively.

**Comment by oliverstotz** [comment]
hi, did what you suggested.
so it must be the filmDS.dll plugin that introduces the error. 
when i removed it, the "filmQT.dll" plugin loads the files and the frames are displayed correctly.

**Comment by umlaeute** [comment]
confirmed

**Comment by umlaeute** [comment]
afaict, the issue is fixed in general, but sometimes DirectShow simply reports that it has successfully seeked to a given frame, while in reality it has not - leading to "hanging" frames.
mostly it seems to work though.
