### ISSUE TITLE
 gemglutwindow ... couldn't create, etc

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#199]
building from latest pull I get:

gemglutwindow ... couldn't create
gemmacoswindow ... couldn't create
etc

something change? 
using wiki instructions to build on macOS 10.14.2

**Comment by megrimm** [comment]
after successful build:
`$ make install libdir=~/Documents/Pd/externals/ prefix=~/Documents/Pd/externals/Gem/stuff`

fails to copy over gemmacoswindow.pd_darwin

**Comment by umlaeute** [comment]
what do you mean with "fails to copy over"? is a copy attempted but does not succeed? is the copy not even attempted?

**Comment by megrimm** [comment]
im not really sure because I do not know how "make install" works. I have always just used:

$ make install libdir=~/Documents/Pd/externals/ prefix=~/Documents/Pd/externals/Gem/stuff

maybe something has changed?

I DO NOT see a copy attempt/error. all I know is Gem/scr/Output/.libs/*.pd_darwin are not installed when running "make install".

**Comment by umlaeute** [comment]
so you do have a `Gem/src/Output/.libs/gemglutwindow.pd_darwin` but no `~/Documents/Pd/externals/Gem/gemglutwindow.pd_darwin`?

could that be a leftover from previous builds?
e.g. do
~~~
$ make -C src/Output clean
$ rm -rf src/Output/.libs
$ make -C src/Output
~~~

and check whether you still have a `gemglutwindow.pd_darwin` in ` src/Output/.libs`.


oh, and you have to run `make install` in the "root-build" directory (aka `.../Gem`); running it in `.../Gem/src` is not enough...though you could run it in `...Gem/src/Output` like so:

~~~
make -C src/Output install libdir=~/Documents/Pd/externals/ prefix=~/Documents/Pd/externals/Gem/stuff
~~~

the above should only(!) install the windowing-externals (`gem*window.pd_darwin`)

**Comment by claudeha** [comment]
I can confirm that the `Gem/src/Output/.libs/*.pd_*` are not copied (on Linux) by `make install` in the top level directory, using current git.  My scenario is admittedly more complicated (trying to build gemsdlwindow with emscripten).

**Comment by umlaeute** [comment]
really weird. here's what i am doing (on my Debian box), using current HEAD (cdd111baeccf009be3ea5d602c047733dd484ad2):

~~~sh
git clone https://git.iem.at/pd/Gem
cd Gem
./autogen.sh
./configure
make -j8
make install DESTDIR=$(pwd)/geminst
find . -name "gem*.pd_linux"
~~~

and it returns:
~~~
./gemglutwindow.pd_linux
./src/Output/.libs/gemglutwindow.pd_linux
./src/Output/.libs/gemglxwindow.pd_linux
./src/Output/.libs/gemsdlwindow.pd_linux
./gemglxwindow.pd_linux
./geminst/usr/local/lib/pd/extra/Gem/gemglutwindow.pd_linux
./geminst/usr/local/lib/pd/extra/Gem/gemglxwindow.pd_linux
./geminst/usr/local/lib/pd/extra/Gem/gemsdlwindow.pd_linux
./gemsdlwindow.pd_linux
~~~

so everything is created as it should be

**Comment by claudeha** [comment]
I think I found the problem (at least in my case): if any one of the `gem*window.*` fails to compile (in my case, it was emscripten not having `freeglut` emulation, only plain `glut` emulation), none of them will be installed at all.  I was working around the error with `make -k`, I didn't succeed in `./configure --without-glut`...

**Comment by megrimm** [comment]
i just fetched latest (be40dd2) and using wiki instructions all seems to work and install as should. window is created, etc.
