### ISSUE TITLE
Mojave: GLEW / OpenGL version error

### ISSUE THREAD

**Issue by Benitoite** [umlaeute/Gem#204]
Have GLEW 2.1.0 installed in /usr/local/lib

GEM loads up fine, but when you create the window, it does not "GLEW":

```
GEM: Graphics Environment for Multimedia
GEM: ver: 0.94.git v0.94_pre1
GEM: compiled  on Dec 21 2018
GEM: maintained by IOhannes m zmoelnig
GEM: Authors :	Mark Danks (original version)
GEM:		Chris Clepper
GEM:		Cyrille Henry
GEM:		IOhannes m zmoelnig
GEM: with help by Guenter Geiger, Daniel Heckenberg, James Tittle, Hans-Christoph Steiner, et al.
GEM: found a bug? miss a feature? please report it:
GEM: 	homepage https://gem.iem.at/
GEM: 	bug-tracker https://bugs.gem.iem.at/
GEM: 	mailing-list https://lists.puredata.info/listinfo/gem-dev/
GEM: compiled for MMX/SSE2 architecture
GEM: using SSE2 optimization
GEM: detected 8 CPUs
GEM: image loading support: magick SGI imageIO jpeg tiff
GEM: image saving support: SGI imageIO jpeg magick tiff
The Pd window filtered 41 lines
Pd documents directory: /Users/rb/Documents/Pd
[gemmacoswindow]: failed to init GLEW: your system only supports openGL-1.0
... you might be able to track this down from the Find menu.
[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!
[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!
[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!
[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!
[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!

```

Everything copied over to a 10.12.6 system and it seems to work fine.

```
GEM: Graphics Environment for Multimedia
GEM: ver: 0.94.git v0.94_pre1
GEM: compiled  on Dec 21 2018
GEM: maintained by IOhannes m zmoelnig
GEM: Authors :	Mark Danks (original version)
GEM:		Chris Clepper
GEM:		Cyrille Henry
GEM:		IOhannes m zmoelnig
GEM: with help by Guenter Geiger, Daniel Heckenberg, James Tittle, Hans-Christoph Steiner, et al.
GEM: found a bug? miss a feature? please report it:
GEM: 	homepage https://gem.iem.at/
GEM: 	bug-tracker https://bugs.gem.iem.at/
GEM: 	mailing-list https://lists.puredata.info/listinfo/gem-dev/
GEM: compiled for MMX/SSE2 architecture
GEM: using SSE2 optimization
GEM: detected 4 CPUs
GEM: image loading support: magick SGI imageIO jpeg tiff
GEM: image saving support: SGI imageIO jpeg magick tiff
GLEW version 1.13.0
```

Of course OpenGL is not v1.0 on Mojave.  Any hints on how to get GEM and GLEW working together in Mojave. I'm out of ideas.    macOS 10.14.3𝛃18D38a

**Comment by umlaeute** [comment]
i can now confirm this behaviour
for me it
- works on `macOS-10.12.6 Sierra` (although `[gemmacoswindow]` doesn't report any keypresses)
- does **not** work on `OSX 10.11.6 El-Capitan`

However, `[gemglutwindow]` and `[gemcocoawindow]` both work nicely on *El-Capitan*
On *Sierra*, `[gemglutwindow]` works good, but `[gemcocoawindow]` doesn't refresh automatically (#182)

**Comment by Benitoite** [comment]
Excellent, building Gem from latest `master` seems to work! Thanks for looking into it.

This is the simplest of tests, as I have yet to study Gem:
![screen shot 2019-01-10 at 9 48 49 am](https://user-images.githubusercontent.com/17919239/50986937-ff3b6300-14bc-11e9-9e50-5c95fe3f5012.png)

`[gemwin]`  window opens, shows cube.
`[gemglutwindow]` window opens, shows only all black.
`[gemcocoawindow]` window opens, shows only all red.

**Comment by umlaeute** [comment]
as a side note: `[gem*window]` are not a replacement for `[gemwin]`, but used to implement `[gemwin]` (which is an abstraction).
as such, it is not surprising, that a single `[gemglutwindow]` does not produce any output. see the `[gemwin]`
