### ISSUE TITLE
AUTO_REGISTER_CLASS runs before main when statically linked to executable

### ISSUE THREAD

**Issue by claudeha** [umlaeute/Gem#205]
`src/Base/CPPExtern.h:AUTO_REGISTER_CLASS` may be ok for a library that will always be dynamically loaded after the main program has a chance to initialize (lib)pd's internals, but when statically linked (for example in emscripten) the program crashes before main in `gemsym()` because the symbol table is not ready.

See also: https://isocpp.org/wiki/faq/ctors#static-init-order 

@umlaeute commented on IRC:

> i guess the only way forward would be to have the AUTO_REGISTER_CLASS register a list of callbacks which are then called by Gem_setup() (after libpd_init())

My temporary workaround for now is `CXXFLAGS="-DNO_AUTO_REGISTER_CLASS"` and writing a manual Gem_setup2() that calls all the things I need.

**Comment by claudeha** [comment]
I got fed up with listing everything, so I made a simple linked list: https://github.com/claudeha/Gem/commit/ab1ff61266bff82be3087ee05f0c05e01a4f3c5b

**Comment by umlaeute** [comment]
right. that's about what i had in mind. thx
