### ISSUE TITLE
gemsdlwindow updates for SDL2

### ISSUE THREAD

**Issue by claudeha** [umlaeute/Gem#206]
gemsdlwindow seems to be for obsolete SDL 1.x, needs quite some changes to compile with SDL 2.y.

The good news: I think I've partially done it in my local fork (in the context of emscripten).

The bad news: while SDL2 supports multiple windows, there is still only one global SDL event queue, and I haven't figured out how to go about sorting events to the correct windows (this may need keeping track of focus enter/leave events, which have windowID associated).

**Comment by umlaeute** [comment]
afaict, all (interesting) `SDL_Event`s have a `windowID` member, that can be used to identify the origin

- https://wiki.libsdl.org/SDL_KeyboardEvent
- https://wiki.libsdl.org/SDL_MouseButtonEvent
- https://wiki.libsdl.org/SDL_MouseMotionEvent

**Comment by umlaeute** [comment]
implemented with 35a3996c1cf90c7be13853c87dcf8e733b86b13a...1c0b5c49606eee1414e6f00e1b948b4fd4aabcfb

not very well tested, though.
