### ISSUE TITLE
Mojave frame rate is bad unless GLUT prefs set to debug mode

### ISSUE THREAD

**Issue by Benitoite** [umlaeute/Gem#207]
This is occurring on macOS 10.14.3b Mojave but not Sierra.  To obtain a reasonable frame rate I have to either select the GEM window and wave the mouse around, or set the window's GLUT preferences to debug mode.

![screen shot 2019-01-14 at 8 12 32 am](https://user-images.githubusercontent.com/17919239/51125327-3cf9fd80-17d5-11e9-92e4-597fd363d740.png)

Example patch:
https://raw.githubusercontent.com/Benitoite/pure-data_patches/master/3cubesTest1.pd

**Comment by umlaeute** [comment]
i've seen something similar today, on a students `Sierra` machine (although i don't know whether this was with `[gemglutwindow]`)

**Comment by umlaeute** [comment]
out of interest: how do you get to the *GLUT preferences* dialog?

**Comment by Benitoite** [comment]
@umlaeute I can only get it on Mojave.  You must select the GEM window first, then access the Prefs in the Pd menu.  On Mojave, when the GEM window is selected, the prefs lead to the GLUT dialog as above.  On Sierra, it does not.

**Comment by umlaeute** [comment]
another thing: i'm wondering, whether Gem is being blocked when switching to the GLcontext (that is: for each render-cycle) or if only the window doesn't redraw itself (unless you "damage" it by moving the pointer).

so, could you measure the actual framerate you get?
something like:

~~~
[gemhead]
|
[t  b   b]
|        |
[realtime]
|
[print]
~~~

**Comment by Benitoite** [comment]
In summary:

|  `  [gemwin]` test  |  Mojave  | Sierra |
| ---: | --- | ---|
| Standard | 16.66 fps  | 19.89 fps  |
| Waving mouse | 76.96 fps  | n/a  |
| Debug mode | 19.88 fps  |  n/a |


|  `[gemwin 40]` test  |  Mojave  | Sierra |
| ---: | --- | ---|
| Standard |  14.32 fps |  40.66 fps  |
| Waving mouse | 153.1 fps  | n/a  |
| Debug mode | 40.66 fps   |  n/a |

<hr>


For the test of [gemwin] default:
![screen shot 2019-01-15 at 1 15 23 am](https://user-images.githubusercontent.com/17919239/51170386-331edb80-1863-11e9-8ff2-6b43c9588027.png)

Standard window on macOS 10.14.3β _Mojave_:
```
print: 61.022
print: 58.872
print: 60.038
print: 61.028
```
<hr>
Waving the mouse around with GEM window selected

```
print: 15.866
print: 15.772
print: 10.317
print: 10.018
```
<hr>
GLUT debug mode `on`

```
print: 49.994
print: 50.059
print: 49.577
print: 51.543
```
<hr>


macOS 10.12.6 _Sierra_
```
print: 50.349
print: 50.193
print: 48.568
print: 51.956
```
<hr><hr>
For the second test: [gemwin 40]

![screen shot 2019-01-15 at 1 27 15 am](https://user-images.githubusercontent.com/17919239/51171109-dc1a0600-1864-11e9-85bb-8187d6500a7e.png)

Standard window on macOS 10.14.3β _Mojave_:

```
print: 80.008
print: 60.091
print: 79.989
print: 59.335
```
<hr>

Waving mouse around with GEM window selected:

```
print: 8.036
print: 5.96
print: 4.071
print: 8.064
```
<hr>

With GEM window in GLUT debug mode:

```
print: 25.485
print: 23.646
print: 26.369
print: 25.182
```
<hr>

macOS 10.12.6 _Sierra_

```
print: 24.181
print: 25.015
print: 24.253
print: 24.921
```

**Comment by umlaeute** [comment]
so it's really blocking. :bummer:

**Comment by umlaeute** [comment]
i did a bit of research, and haven't found anything to fix this programmatically.

for now, i'd suggest to just enable `Debug mode` in the *GLUT preferences* and live happy ever after (afaict, the settings are sticky, so you only have to do that once per machine.)

**Comment by umlaeute** [comment]
i think the only proper solution for this is to not use `[gemglutwindow]`, and instead us `[gemglfw3window]` which is supposed to be much better anyhow :-)

i'm closing this, as i don't plan on "fixing" the GLUT rendering on macOS, and there are viable alternatives
