### ISSUE TITLE
ggemcocoawindow.mm:378:1: error: version control conflict marker in file

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#212]
after:

```
$ ./configure --with-pd=/Applications/Pd.app/Contents/Resources --with-defaultwindow=gemmacoswindow --without-ImageMagick
$ make
```

get the following now :

```
gemcocoawindow.mm:248:1: error: version control conflict marker in file
<<<<<<< HEAD
^
gemcocoawindow.mm:263:1: error: version control conflict marker in file
<<<<<<< HEAD
^
gemcocoawindow.mm:378:1: error: version control conflict marker in file
<<<<<<< HEAD
```
20 warnings and 3 errors generated.
make[1]: *** [gemcocoawindow_la-gemcocoawindow.lo] Error 1
make: *** [all-recursive] Error 1

lots of depreciation warnings. maybe gemcocoawindow need not be compiled if configure with --with-defaultwindow=gemmacoswindow 

macOS 10.14

**Comment by umlaeute** [comment]
that seems to be a local conflict on your machine.
