### ISSUE TITLE
[gemglxwindow] crashes in texture sharing example with intel card

### ISSUE THREAD

**Issue by mxa** [umlaeute/Gem#214]
in 14.multiple_windows/03.texture_sharing
clicking on the bang message results in Pd quitting with the message:

~~~
i965: Failed to submit batchbuffer: Invalid argument
~~~

Linux64bit compiled from git

**Comment by umlaeute** [comment]
i guess, this is with `[gemglxwindow]` as a windowing backend

**Comment by mxa** [comment]
no idea, what's that?

**Comment by umlaeute** [comment]
you can use GLUT, SDL, SDL2, GLFW, GLFW3 and GLX to create windows (on linux; on macOS and W32 there are other options).
all of them behave slightly different.

currently, the only way to find out which windowing backend is used is by opening the `[gemwin]` abstraction, looking for the `[gemdefaultwindow]` abstraction inside the `[pd window]` subpatch and see what's in there.
(the only way to change the backend is to modify the `[gemdefaultwindow]` abstraction.

**Comment by mxa** [comment]
I see! So the answer is yes, that's with `[gemglxwindow]`.
