### ISSUE TITLE
double free or corruption (fasttop) Pd: signal 6

### ISSUE THREAD

**Issue by mxa** [umlaeute/Gem#215]
steps to reproduce:
open examples/12.multi_screen_projection/01.flat_projection-help.pd
create gemwin via toggle in patch
close gemwin via toogle in patch
close patch

results in

double free or corruption (fasttop)
Pd: signal 6

**Comment by umlaeute** [comment]
afaict, that was fixed with 4add051aa7ebf763a4b0d5cc958f4300e54c0922

**Comment by mxa** [comment]
confirming fix
