### ISSUE TITLE
fails to build after `./configure --enable-Vertex`

### ISSUE THREAD

**Issue by claudeha** [umlaeute/Gem#217]
./configure --enable-Vertex
    make -k
    make -k > make.log 2>&1

[make.log](https://github.com/umlaeute/Gem/files/2788652/make.log)

**Comment by umlaeute** [comment]
somewhat fixed, but the Vertex/ stuff is not really supported these days (i'm usually very reluctant to remove stuff entirely).

"somewhat" means, that - while i fixed the minor issues,  i also disabled `[vertex_model]` completely (which is probably one of the more interesting objects)
