### ISSUE TITLE
Segmentation fault: 11 loading glsl shader macOS

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#219]
With any of the 10.glsl examples Pd crashes immediately with Segmentation fault: 11 when attempting to load a shader.

macOS 10.14.2

**Comment by umlaeute** [comment]
which version?
could you try the nightly builds (as described in #218 )

**Comment by megrimm** [comment]
>> which version?

Just did a fetch right before i logged issue so 279f885

Although i noticed this happened a few days ago but did not log issue so maybe the problem commit is back a ways?

>>could you try the nightly builds

same with nightly builds.... immediate crash.

**Comment by umlaeute** [comment]
i think i found the culprit: 61438c5e4c80fe74182f70553e00aa9ad9721b7f introduced uniform arrays (see #183), and on macOS i cannot query the length of the array...

**Comment by umlaeute** [comment]
the exact problem is that `glGetActiveUniformsiv` is `NULL` in [glsl_program.cpp:838](https://github.com/umlaeute/Gem/blob/b768af87a4a13c7d99026be59fbc0b44773f9d86/src/Manips/glsl_program.cpp#L838)
