### ISSUE TITLE
[model] ASSIMP3 bad rendering with .obj files

### ISSUE THREAD

**Issue by r33p** [umlaeute/Gem#222]
the problem :
when I choose the ASSIMP3 backend
I can load an .obj file, but it looks bad (problem on the faces indexes ?).
(see attached patch)

notes :
the OBJ backend works fine with .obj files
ASSIMP3 works fine with .blend files
pd 0.49
ubuntu 18.04
gem from git

[model_bug.zip](https://github.com/umlaeute/Gem/files/2814100/model_bug.zip)

**Comment by r33p** [comment]
![model_bug](https://user-images.githubusercontent.com/1814233/52007283-71a4cf00-24ce-11e9-8f7a-d9e2a6f10ceb.png)
screenshot

**Comment by umlaeute** [comment]
confirmed. sigh.
maybe its a problem with assimp?

**Comment by r33p** [comment]
it is strange because some models seems to work, and some others don't...
so it may be related to how the .obj files are made ?
will try to investigate a bit further this weekend...

**Comment by umlaeute** [comment]
just a quick note: the problem in the example is the `Highr5` object (the 2nd from left). all the other problems are directly related to rendering this object.

**Comment by umlaeute** [comment]
simplified object exposing the problem:
[highr5.zip](https://github.com/umlaeute/Gem/files/3616587/highr5.zip)

**Comment by r33p** [comment]
Thanks IOhannes !

**Comment by umlaeute** [comment]
it took a while :-)
