### ISSUE TITLE
gemglxwindow texture sharing regression

### ISSUE THREAD

**Issue by kubriel** [umlaeute/Gem#226]
i am able to run gemglxwindow with texture sharing with git compiled gem from 7. dec 2018.

**Comment by umlaeute** [comment]
so what is the issue?

**Comment by kubriel** [comment]
its not working in recent builds, and in examples/14.multiple_windows/03.texture_sharing.pd is written "on Linux, this is only supported by [gemglutwindow]." so i was guessing that it was disabled because of some other problem?

**Comment by umlaeute** [comment]
yes, see df50a436b1f8bb3be47e5299f9190c35ba9fffc0 where it was disabled.
(i don't really see it as a regression, which i only consider between releases, not during development).

**Comment by kubriel** [comment]
ok now i know i can enable it whenever i want, but why it is disabled if it is working?

**Comment by umlaeute** [comment]
did you read df50a436b1f8bb3be47e5299f9190c35ba9fffc0? it links to #87 and #214 which are two issues that are detrimental to "working".

**Comment by kubriel** [comment]
i have to say that i was happy to use gemglxwindow with enabled texture sharing on my intel gpu laptop for the whole night without any suprises. it works with dedicated amd gpu also.
