### ISSUE TITLE
pix_movie slow framerate on Rpi3b+

### ISSUE THREAD

**Issue by mbncr** [umlaeute/Gem#230]
Hello, 
Do you have any recommendation past the basic configuration and codec support for Raspberry Pi 3B+ (Raspbian Stretch)?
I can't find a way to play videos at a proper framerate via GEM, neither with pix_movie nor pix_film.
Clips are short (4 sec max), meant to be played in HD at 30fps, nothing fancy. Tried different encoding, formats, resolutions (.mov x264, .mp4, .mkv, 1080p, 720p,...), different screen resolutions, switched GL drivers, downgraded MESA, flashed a different SD card... but can't get them to play at a proper framerate. Tried both buffer2 and buffer 1 + metro methods.

I'm out of ideas at this point, hope you can help !
Thanks in advance.

**Comment by kubriel** [comment]
did you tried mjpeg in avi? 
ffmpeg -i input -vf scale=720x576 -c:v mjpeg -q:v 2 -an output.avi

**Comment by mbncr** [comment]
Just tried, with no success.

**Comment by umlaeute** [comment]
load the video into a `[pix_buffer]` and read it from RAM.

**Comment by mbncr** [comment]
does not work either.

**Comment by kubriel** [comment]
what is resolution of video you try to play? also.. what backend are you using to read files? i found gmerlin a bit more efficient at least on amd64.

**Comment by umlaeute** [comment]
> does not work either.

what does that mean?

**Comment by kubriel** [comment]
[pix_film] and [pix_movie] has different backend plugins for decoding video. depending if you installed gem-plugin-lqt or gem-plugin-gmerlin. but performance difference on mjpeg is only slight difference, so it may not be sufficient if you have big troubles.

**Comment by umlaeute** [comment]
@kubriel using `[pix_buffer]` (if done properly ;-)) will effectively separate the decoding stage from the playback stage, so the performance of the decoder should have no impact on the playback.

which leaves only the openGL-drivers of the RPi. which is probably bad enough to not being able to handle such data transfers.

but @mbncr 's "does not work" without further information only allows for pure speculation, which i'd rather not spend my time on.

**Comment by mbncr** [comment]
@kubriel Thanks for the cue. Both gem-plugins are installed, and with playback only, I did not notice a significant difference between the two objects. TBH, I couldn't compare further, as to my knowledge, only pix_film works with pix_buffer. 

@umlaeute Sorry my previous messages came out wrong, I've taken some time to follow both of your advices and do my homework. Unfortunately, so far no luck

I think it has something to do with encoding rather than the objects themselves, but again, I may be missing something. Here's my patch (using pix_buffer) with a few more info if you want to have a look. [https://github.com/mbncr/Gem-buffer-video-player-Rpi3B-](url)
Thanks for your time,

**Comment by umlaeute** [comment]
@mbncr your buffer-based player seems fine to me.

this however means, that the problem you are facing is not about decoding the video, but instead about transferring the pixel data from the main memory to the gfx-card.

try sending a `[pbo 1(` (or `[pbo 2(`) message to the `[pix_texture]` for asynchronous pixel transfer.
this  will slightly delay the pixel transfer, but should give you better performance.

it this doesn't help either, then i'm afraid it's a limitation of the openGL stack of the RPi3 and Gem cannot do much about it (you could try using [ofelia](https://github.com/cuinjune/ofxOfelia) instead)

**Comment by umlaeute** [comment]
@kubriel wrote:
> [pix_film] and [pix_movie] has different **backend plugins** for decoding video

@mbncr answered:
> Both gem-plugins are installed, and with playback only, I did not notice a significant difference between the two **objects**.

i think there's some language barrier here.
`[pix_movie]` and `[pix_film]` can use *multiple* backend plugins for decoding video. some (e.g. gmerlin) might perform better than others (e.g. lqt).
however, both `[pix_movie]` and `[pix_film]` use the *same* backends (`[pix_movie]` is mostly a wrapper around `[pix_film]` + `[pix_texture]`).

**Comment by Ant1r** [comment]
> (you could try using [ofelia](https://github.com/cuinjune/ofxOfelia) instead)

or [Pof](https://github.com/Ant1r/ofxPof) ;-)

**Comment by mbncr** [comment]
Thanks for the tips @umlaeute @Ant1r !
I will try all solutions and will get back to you if anything relevant comes up.
