### ISSUE TITLE
linux: After building from source, [pix_video] fails to detect any camera

### ISSUE THREAD

**Issue by jamshark70** [umlaeute/Gem#241]
I had been using Gem 0.93 installed from Ubuntu 18.04 packages. No problem with pix_film or pix_video. But, some of the help patches were crashing against Pd 0.50, so I thought I should upgrade.

https://packages.debian.org/buster/gem -- unclear to me if this is valid for Ubuntu Studio 18.04.

A member on the Pd forum suggested that I build from source. So I cloned the repository, 'autogen' 'configure' 'make' etc. This went relatively painlessly, except that I had to do it twice because the current README, as far as I can see, doesn't mention required packages to build the video plug-ins. After installing those packages, [pix_film] is working.

BUT [pix_video] is not.

At startup: `GEM: video capture plugins: dc1394`

Opening a patch that contains a [pix_video] object: `[pix_video]: backend #0='dw1394' : dw1394 iidc` (and for some reason, at this point, I can no longer copy text from the console)

Turning on rendering: `[pix_video]: no valid video backend found` and the camera light doesn't turn on.

So I suppose I need to install some other package(s), but the current README contains not much detail about ~~building in Linux~~ Linux build requirements.

In any case, the current situation is that a Linux user can build Gem from source, but some features are disabled. So the documentation seems insufficient.

> Operating-System (kernel-version,...)

Linux ---- 4.15.0-70-lowlatency #79-Ubuntu SMP PREEMPT Tue Nov 12 11:30:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

> video-card, driver

No problems with video rendering.

> other hardware that is related to your problem (e.g.: camera)
> does your system work with similar applications (e.g.: capture-software,
> openGL (games, "glxgears")

Can't find the camera ID but Skype can open the camera without any problem. Also, the older version of Gem could use the camera.

> what is the output of pd when you start it with the "-verbose" flag
> (e.g.:"pd -verbose -lib Gem")

"tried /usr/local/lib/pd/extra/Gem/Gem.pd_linux and succeeded" but others failed.

**Comment by kubriel** [comment]
i believe you are missing libv4l-dev package, so your gem_videoV4L2.so is not builded

**Comment by jamshark70** [comment]
> i believe you are missing libv4l-dev package, so your gem_videoV4L2.so is not builded

Ah, OK, installed libv4l-dev and rebuilt. Now it's working.

```
$ grep libv4l ~/share/pd/Gem/README.txt
$
```

Feel free to close (though I'd suggest this sort of detail should be documented with the build instructions).

**Comment by umlaeute** [comment]
btw, the build requirements on Debian-based systems can be simply installed with

~~~
apt-get build-deps gem
~~~
