### ISSUE TITLE
make install not installing gemwin binaries

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#245]
not a huge problem but i noticed that when I do:

`make install libdir=~/Documents/Pd/externals/ prefix=~/Documents/Pd/externals/Gem/stuff`

gemmacoswindow.pd_darwin, etc are not installed to the specified directory,  so error when putting [gemwin] on canvas.

**Comment by megrimm** [comment]
ha... i did not remember this issue was submitted before at https://github.com/umlaeute/Gem/issues/199 although I am assuming its still an issue since it happened again.

**Comment by megrimm** [comment]
Think this is it.  I assume make install stops before installing gem*window.pd_darwin when trying to install videoDECKLINK and it can not.

```
Making install in videoDECKLINK
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/megrimm/Development/puredata/pd-gem/gem/plugins/videoDECKLINK/missing aclocal-1.15 -I ../../m4 -I .
/bin/sh: /Users/megrimm/Development/puredata/pd-gem/gem/plugins/videoDECKLINK/missing: No such file or directory
make[2]: *** [aclocal.m4] Error 127
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

**Comment by umlaeute** [comment]
hmm, it would be interesting to know why/how the `videoDECKLINK` fails to compile/install.

apart from that:
- the option is really called `--without-DeckLink` (note the capitalisation!)
- this *is* in the configure-help, but since we are using recursive `autoconf`-invocation, it only shows up for

      ./configure --help=recursive

  (i've updated the README.txt to include this)

**Comment by megrimm** [comment]
with `./configure --help=recursive` I get:

`configure: WARNING: no configuration information is in plugins/videoDECKLINK`

not sure why it fails but `gem/plugins/videoDECKLINK/missing` does not exist for me, obviously. is it supposed to?

>>the option is really called --without-DeckLink (note the capitalisation!)

ah the capitalization... got it!

**Comment by umlaeute** [comment]
> configure: WARNING: no configuration information is in plugins/videoDECKLINK 

is that after you hacked the `plugins/Makefile.am` or with a pristine copy?

**Comment by megrimm** [comment]
it might be possible running `$ autoreconf --install --verbose` did not generate the necessary files?  I ran it on a "pristine copy" and everything seems to be OK so I am just assuming something went wrong with my copy. I'll open a new issue if something else goes wrong. I think this issue can close.
