### ISSUE TITLE
assimp/cimport.h: present but cannot be compiled

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#247]
hey i noticed this so im reporting:

```
checking assimp/cimport.h presence... yes
configure: WARNING: assimp/cimport.h: present but cannot be compiled
configure: WARNING: assimp/cimport.h:     check for missing prerequisite headers?
configure: WARNING: assimp/cimport.h: see the Autoconf documentation
configure: WARNING: assimp/cimport.h:     section "Present But Cannot Be Compiled"
configure: WARNING: assimp/cimport.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------ ##
configure: WARNING:     ## Report this to zmoelnig@iem.at ##
configure: WARNING:     ## ------------------------------ ##
checking for assimp/cimport.h... no
```

macOS 10.14.6

**Comment by umlaeute** [comment]
it seems that this is a weird coincidence of
- clang on your (and my...) system defaulting to C++98
- assimp requiring at least C++11
- assimp not declaring this in their `pkg-config` script
   - the `pkg-config` script of assimp seems to be somewhat broken with brew anyhow, but i doubt that this the problem of the C++-version is fixable via `pkg-config` in general
- sloppy code in Gem's autotools code (that would prevent a somewhat easy fix for the problem)

anyhow, i've fixed the `configure.ac` to be less sloppy.
with that fix applied, you should be able to properly detect assimp *iff* you tell the compiler to se at least C++11. e.g.:

    ./configure CXXFLAGS="-std=c++11 -g -O2"

a more specific workaround would be:

    ./configure PKG_ASSIMP_CFLAGS="-std=c++11 $(pkg-config --cflags assimp)" PKG_ASSIMP_LIBS="$(pkg-config --libs assimp)"

even better would be to replace `$(pkg-config --cflags assimp)` by a fixed version of the output of `pkg-config --cflags assimp` (here it outputs `-I/usr/local/Cellar/assimp/5.0.1/../include/include` whereas it should output `-I/usr/local/Cellar/assimp/5.0.1/include`; note that you need to add the `-std=c++11` in *any case*)

**Comment by umlaeute** [comment]
ha, at least the assimp pkg-config problems are already known and fixed https://github.com/assimp/assimp/issues/2804

i'm a bit reluctant to add a `-std=c++` flag to the default Gem-flags, due to https://stackoverflow.com/questions/60857699/

**Comment by umlaeute** [comment]
and it seems that the underlying problem (assimp requiring `c++11` has been fixed in  https://github.com/assimp/assimp/commit/031d3b648ea98bdc6b61b4925bdc1137ff5fcb95

so with the next assimp release, this problem should disappear.
