### ISSUE TITLE
[pix_film] hangs well before the last frame of the video

### ISSUE THREAD

**Issue by jamshark70** [umlaeute/Gem#252]
Working on a demo for a class. I loaded a 4-second mp4 into [pix_film] (96 frames -- the "length" reported by [pix_film]).

I can access frames 0 to 93 by number. Accessing frames 94 or 95 causes Pd to hang. I have to force-kill it and relaunch.

Expected behavior: If the video has 96 frames, all 96 of them should be accessible. Or, if not accessible, it should at least not crash the whole program.

Actual behavior: The last couple of frames are fatal.

**Comment by kubriel** [comment]
not happening here.
but gem runs on multiple platforms which handles these things very differently. thats the reason why plugin system is used to handle media files if im right. so i guess you forgot to mention what OS are you running, and what video backend your gem uses to load files.

**Comment by jamshark70** [comment]
Linux (Ubuntu Studio)... I didn't check the backend, but it should be whatever the default is. (I built Gem from source myself for the sake of [pix_video] but I didn't customize any build settings for [pix_film].)

Anyway, I think for the class, I'll just tell the students to edit the video with extra frames at the end, and then just don't use all of them.

**Comment by umlaeute** [comment]
the "default" backend depends on which development-libraries/headers have been available at build-time, so there's no telling.

**Comment by jamshark70** [comment]
Apologies for dropping this issue.

How would I verify which backend is being used?

**Comment by umlaeute** [comment]
try starting Pd in "verbose" mode, you should get a bit more information on the Pd-console (and possibly on the terminal) when loading the video file.

**Comment by umlaeute** [comment]
also, when you should get a list of available backends when:

- starting Gem, like:

~~~
GEM: film loading plugins: gmerlin quicktime4linux
~~~

- instantiating the `[pix_film]` object (with `Log-Level >= 3 (debug)`):

~~~
[pix_film]: gmerlin support
[pix_film]: quicktime4linux support
[pix_film]: image support
~~~

- when sending a `[loader(` message (without args) to `[pix_film]`:

   -  in the console:

    ~~~
    [pix_film]: loader[0] gmerlin
    [pix_film]: loader[1] quicktime4linux
    [pix_film]: loader[2] image
    ~~~

   -  at the 3rd outlet:

    ~~~
    A: loaders 3
    A: loader gmerlin
    A: loader quicktime4linux
    A: loader image
    ~~~

- finally you can choose which loader to prioritize with the `[loader(` message (e.g. `[loader quicktime4linux(` will try the *qt4l* loader first, even if it usually would prefer the *gmerlin* loader)

**Comment by jamshark70** [comment]
It's a year and a half later and I can't reproduce this anymore -- probably due to a system update, or codec being updated by something in the OS. I'll close this.
