### ISSUE TITLE
[gemkeyboard] and [gemkeyname] have no output on mac osx

### ISSUE THREAD

**Issue by unknownError** [umlaeute/Gem#253]
[gemkeyboard] and [gemkeyname] on Gem / Pd Vanilla don't report any keyboard events. 

tested:
[gemkeyboard]
|
[print]

same for [gemkeyname]

clicking into Gemwin, then trying various keys

pd 0.50-2
gem 0.94.git (installed through deken)
mac osx 10.15.2

**Comment by mrpropre** [comment]
Yes, the workaround is to create a [gemcocoawindow] object in your patch in OSX.
It will update key event, but not in fullscreen...

**Comment by unknownError** [comment]
thanks. that's especially useful to know as [key] seems to crash vanila too currently... :)

**Comment by umlaeute** [comment]
the default window backend is now `[gemglfw3window]` which does report keys on macOS.
