### ISSUE TITLE
GIF frame rate not read using [pix_film]

### ISSUE THREAD

**Issue by hellocatfood** [umlaeute/Gem#254]
I am able to play an animated gif via [pix_film] but for some gifs the playback speed is very fast. For example:

![elmodancing](https://user-images.githubusercontent.com/151947/82320175-c07bbe00-99ca-11ea-9f96-8ba7b2e05aaa.gif)

This gif has a delay of 100ms between each frame. However, when played in Gem via [pix_film] this is what it looks like

[videoplayback.zip](https://github.com/umlaeute/Gem/files/4649999/videoplayback.zip)
(original gif on the left, Gem output on the right)

When loading the gif the Pd message window correctly shows the frame rate:
```
verbose( 0):[pix_film]: gmerlin support
verbose( 0):[pix_film]: quicktime4linux support
verbose( 0):[pix_film]: MPEG3 support
verbose( 0):[pix_film]: aviplay support
verbose( 0):[pix_film]: image support
verbose( 0):[GEM:filmGMERLIN:fileindex] Built file index in 0.00 seconds
[pix_film]: loaded file: /home/hellocatfood/Desktop/elmodancing.gif with 8 frames (90x120) at 10.000000 fps
[gemglxwindow]: Direct Rendering enabled!
```
However the playback is still sped up.

I'm using gem 0.94 on Pd 0.50.2 on Ubuntu 20.04

**Comment by umlaeute** [comment]
how do you play back?

Gem (mostly) doesn't do any framerate adjustment, but all the info is exposed on the patch level so that you can do it yourself :-)

**Comment by hellocatfood** [comment]
I'm playing back using [auto ( . Gem is playing back most gifs that I give it at the correct spend but some are faster, and I don't understand why.

**Comment by umlaeute** [comment]
could you also share a gif that plays back at the correct speed?

do those that play back correctly have something in common? (like a nominal fps that matches the one you are using in Gem)

**Comment by umlaeute** [comment]
in any case: the code as is will just proceed to the next frame of the film (or gif, in your case) for each rendering tick (taking into account the auto-speed, but happily ignoring the nominal framerate of the film).

i understand that the possibility to "just play back at the correct speed" is desirable and *probably* expected from the `[auto(` message.

however, changing the behaviour might actually break existing patches. so i'm not sure how to proceed...

**Comment by umlaeute** [comment]
the solution is simply to set the playback speed to `gemframerate/filmframerate`, like this:

![pix_film with corrected speed](https://pastie.iem.at/view/raw/98608e11.pd.svg)

(if you know the framerate beforehand, the patch is of course much simpler)


as i still think that the current behaviour is not going to change, i'm closingthis as "wontfix"

**Comment by umlaeute** [comment]
oh my. the original patch is available under https://pastie.iem.at/view/98608e11 (i forgot to link, and it seems gitlab proxies any external images...)
