### ISSUE TITLE
pix_record couldn't initialize codec

### ISSUE THREAD

**Issue by Reinissance** [umlaeute/Gem#255]
Hi,
pix_record isn't working on my machine: When opening the patch (or pix_record-help-pd) console says

GEM: image loading plugins: magick SGI STB imageIO jpeg tiff
GEM: film loading plugins: AVF quicktime4linux
GEM: image saving plugins: SGI STB imageIO jpeg magick tiff
GEM: model loading plugins: ASSIMP3 OBJ
GEM: video record plugins: QT4L
GEM: video capture plugins: AVF decklink
[pix_video]: backend #0='AVF'	: AVF 
[pix_video]: backend #1='decklink'	<--- DISABLED

But when starting to record it says

[GEM:recordQT4L] couldn't initialize codec
[GEM:recordQT4L] unable to initialize QT4L

I'm on osx 10.15.5

Any suggestions?

Regards,
Reini

**Comment by Reinissance** [comment]
Same on osx 10.14...

**Comment by Reinissance** [comment]
I tried to compile Gem myself, first installed dependecies requested by autogen.sh plus pkg-conf with brew (also changed autogen.sh to look for glibtool & glibtoolize in a second attempt), but it runs very slow with audio dropouts.
But pix_record ceased complaining it couldn't initialize the codec - instead says "unable to open file path/to/file.mov"...
Do I have to to add any optional flags, frameworks (like avframework) or libraries (decklink?) I missed?

Step by step:
cloned gem
changed autogen.sh to use glibtool and glibtoolize
ran autogen.sh
ran ./configure --with-pd=/path/to/src/in/applications/pd.app/contens/resources/
ran make
ran make install
copied contents from /usr/local/lib/pd/extra to /path/to/applications/pd.app/contens/resources/extra

Thanks for your help

**Comment by kubriel** [comment]
i believe its not recomended to run gem together with audio in puredata. i usually run two instances of puredata, one for audio, other for video, and comunicate between them via netsend/netreceive on localhost. it appeared to be very convinient when you decide to run one of them on different machine.

**Comment by umlaeute** [comment]
there currently isn't a backend for video-output on OSX.

- the QT4L backend is really linux-only ("QT4L" is an abbreviation for "QuickTime for Linux")
- the QT backend works on OSX (and Windows), but it is 32bit only (that's because Apple decided that QuickTime will never exist on 64bit).

you might want to try the syphon external for Gem.
