### ISSUE TITLE
04.binary_tree.pd is not branching

### ISSUE THREAD

**Issue by kubriel** [umlaeute/Gem#256]
examples/13.recursion/04.binary_tree.pd
examples/13.recursion/05.n-ary_tree.pd
are not branching.
maybe i misunderstood it, but i would expect something different from what i got:
http://kubriel.servus.at/uploads/lsystems.png

i tested debian buster package, fresh git version on linux and also windows deken installed gem

**Comment by umlaeute** [comment]
actually it is branching, you just don't notice...
