### ISSUE TITLE
pix_buffer save doesn't accept relative paths

### ISSUE THREAD

**Issue by jamshark70** [umlaeute/Gem#258]
Saved a patch in a specific location. There's an image 'oil.jpg' in the same location.

[pix_image oil.jpg] can read it.

I do some stuff to write it into a pix_buffer.

```
[save test.jpg 0(
|
[pix_buffer a 1]
```

No file is written. `[save ./test.jpg 0(` also writes nothing.

`[save /home/dlm/test.jpg 0(` *does* write a file to my home directory (not where I want it).

If [pix_image] can read from a relative path, other GEM objects should be able to write to relative paths.

**Comment by umlaeute** [comment]
relative to what?

when *reading* a relative path, Pd iterates through all the search paths until it finds a file with the given name.
one of these search paths is the patch directory.

when *writing*, iterating makes much less sense (we don't want to write the file too *all* places).
so what we use as the base for writing relative paths is the *working directory* from where Pd was started.

~~~sh
$ cd /tmp/foobar
$ ls -lha
total 28K
drwxr-xr-x  2 user user 4.0K Aug 27 22:51 .
drwxrwxrwt 24 root root  20K Aug 27 22:52 ..
$ pd -lib Gem
# record to a [pix_buffer] and click  on [save test.jpg 0(
# then quit Pd
$ ls -lha
total 80K
drwxr-xr-x  2 user user 4.0K Aug 27 22:51 .
drwxrwxrwt 24 root root  20K Aug 27 22:52 ..
-rw-r--r--  1 user user  50K Aug 27 22:53 test.jpg
~~~

when starting Pd from the desktop shortcut, the pwd would typically be your home directory.

checkout `[pdcontrol]` to get the full path of your current patch.

**Comment by jamshark70** [comment]
> so what we use as the base for writing relative paths is the working directory from where Pd was started.

I can accept the use of pdcontrol to set the path explicitly, but... this is counterintuitive. Just about everywhere else in Pd, the patch's saved location is the first place to read from or write to. I just checked soundfiler -- relative paths go to the patch directory.

![soundfiler-write](https://user-images.githubusercontent.com/318301/91513083-0fb08380-e916-11ea-8634-7187150e4e27.png)

The reasoning is, of course, sound about not writing to all locations -- but for reading, one doesn't resolve a relative path to all possible locations either. We check them in sequence and accept the first one that works. There's no inherent reason why that same logic wouldn't apply to writing. If the patch's saved location is the first one checked, then you have solid reasoning and intuitive behavior.

I can accept also that changing the behavior may break backward compatibility and I'm happy to leave the issue closed for that reason. But I don't find the justification for the current behavior compelling.
