### ISSUE TITLE
pix_film second outlet doesn't fire when video is given as a symbol

### ISSUE THREAD

**Issue by jamshark70** [umlaeute/Gem#260]
1. Create a patch as follows:
   ![pix_film-stats](https://user-images.githubusercontent.com/318301/91144022-ffb25d00-e6e5-11ea-8d9e-7bc07c7c3b83.png)
2. Save the patch.
3. Reopen the patch. Pd prints "[pix_film]: loaded file: /media/dlm/7D53-8744/Docs/lc-vids/20-0820-bugs/20-0820-bugs-small.mp4 with 718 frames (540x960) at 25.000000 fps" but there is no print from the [print] box.
4. Now send a message `[open ....path....(` to the pix_film and you'll see the [print] box activate.

pix_film help says the second outlet fires whenever media are loaded, but this is not true: It's only when media are loaded *by an 'open' message*.

So it's basically less useful to specify the video file as a creation argument.

**Comment by umlaeute** [comment]
that just doesn't play together with how Pd works.
when a patch is loaded, there are separate actions for instantiating objects and for connecting them.
obviously, an object needs to exist *before* it can be connected.

now when you create an object `[pix_film /path/to/video.mp4]` the object will instantiate immediately and the film gets loaded. while the `[print]` object might already exist (or not), the connection between the two objects is not yet established.
hence any output that the `[pix_film]` object might generate is lost.

if you need that information, you must defer the loading of the video from *load time* to *init time*.

**Comment by jamshark70** [comment]
Thanks for the explanation. I wondered if loading the file header was synchronous or asynchronous -- so the answer is that it's synchronous.

Will switch it to a loadbang --> open message.
