### ISSUE TITLE
literal "none required" in LIBS when compiling with Emscripten

### ISSUE THREAD

**Issue by claudeha** [umlaeute/Gem#268]
If I don't override `GL_LIBS` settings, when compiling with Emscripten a literal text gets into LIBS:
```
  LIBS                   : none required -ldl -lm 
```
which breaks everything because `none required` are not valid linker options.  `config.log` has
```
GL_LIBS='none required'
```
which I think should narrow down which test is to blame (probably checking link flags for OpenGL)  I don't know enough autotools to fix it myself.

**Comment by umlaeute** [comment]
could you try with `141d199fd205da33bedb84e50abe8ad51d3ca6c2` (this is an older commit, right before merging #251, which (also?) broke openGL-detection on W32...)

**Comment by claudeha** [comment]
I checked out that commit, ran
```
emconfigure ./configure --with-pd=${HOME}/code/github.com/claudeha/libpd/pure-data --disable-multicontext --enable-static --disable-shared
```
which reported
```
checking for CFLAGS needed for OpenGL... ""
checking for LIBS needed for OpenGL... " "
checking for LDFLAGS needed for OpenGL... ""
```
and summarized at the end
```
  LIBS                   : -ldl -lm 
                         : -lftgl -lglfw3 -lglfw   
```
But it also complained about missing GLU, so I added
```
export GLU_CFLAGS="-I${HOME}/code/gitlab.freedesktop.org/mesa/glu/include"
export GLU_LIBS="-L/home/claude/code/gitlab.freedesktop.org/mesa/glu/.libs -lGLU"
```
having compiled GLU previously with Emscripten, and reran the configure, and it seemed to work (as did `emmake make` afterwards),

**Comment by umlaeute** [comment]
thanks for checking.
i think i'm going to revert 2edfde4f0587e72ef325e7f53681936dcc19655b for now.
