### ISSUE TITLE
pix_fiducialtrack assertion failed

### ISSUE THREAD

**Issue by kubriel** [umlaeute/Gem#270]
when i plug yuv, grey, or rgba image to pix_fiducialtrack, pd crash, and i get 
`pd: segment.c:68: new_region: Assertion colour == 0 || colour == 255 failed.
Pd: signal 6`

fresh github gem

**Comment by umlaeute** [comment]
confirmed

**Comment by umlaeute** [comment]
`[pix_fiducialtrack]` actually requires a **black&white** image (e.g as generated with `[pix_threshold_bernsen]`, rather than any other greyscale image.

it shouldn't crash though...

**Comment by kubriel** [comment]
i was probably wrong here, pix_fiducialtrack-help.pd is now working on my setup as is

**Comment by umlaeute** [comment]
well it did crash if you failed to insert a `[pix_threshold_bernsen]` object before the object.
as of 8cc5d52, it no longer crashes (although it doesn't do anything miningful either).

**Comment by kubriel** [comment]
how i was able to ignrore pix_fiducialtrack-help.pd ?
