### ISSUE TITLE
videoNDI red and blue channels are swapped

### ISSUE THREAD

**Issue by kubriel** [umlaeute/Gem#275]
i didnt spend much time testing this issue, because i solved it fast with [pix_colormatrix], but i had to swap red and blue channels, when used [pix_video] to receive NDI stream.

**Comment by umlaeute** [comment]
platform?

**Comment by umlaeute** [comment]
and while you are at it: which version of Gem?
and how do you create the NDI-stream? do other receivers get the colorspace right? (or put otherwise: are you sure that the stream has the colors correct?)

**Comment by kubriel** [comment]
gem NDI input is ok, i was wrong. it was Resolume NDI output swapping colors.
