### ISSUE TITLE
[model] kills [scopeXYZ~]

### ISSUE THREAD

**Issue by sonofluiz** [umlaeute/Gem#276]
Hey so I think `[model]` and `[scopeXYZ~]` are incompatible. I tried just putting the 2 help.pd projects together (scopexyz~help and model-help) and they don't work. Does anyone have experience with using these 2 gem objects at the same time? The problem is `[model]` overrides `[scopeXYZ~]` and `[scopeXYZ~]` disappears as soon an .obj file is loaded into `[model]`

i made some progress using *14.multiple_windows/01.basic_example.pd*. seems like `[model]` and `[scopeXYZ~]` need to be in separate gemwins or gembuffers to work

**Comment by umlaeute** [comment]
confirmed.

**Comment by umlaeute** [comment]
the same is true of `[scopeXYZ~]` and `[gemvertexbuffer]`
