### ISSUE TITLE
building with FTGL on Mac OS X

### ISSUE THREAD

**Issue by avilleret** [umlaeute/Gem#28]
`ftgl` package has been fixed by brew team
but now, when trying to build Gem with FTGL, I got : 

```
/usr/local/Cellar/ftgl/2.1.3-rc5/include/FTGL/ftglyph.h:50:19: error: variable has incomplete type 'class FTGL_EXPORT'
```

complete log is here : https://gist.github.com/avilleret/9a73e77c69c2448a01c2

I notice that `make CPPFLAGS=$(pkg-config --cflags freetype2)` works

since the include path returned by `$(pkg-config --cflags freetype2)` is already there when I do `make` alone, what's the difference ?

**Comment by megrimm** [comment]
just a note: on a clean 10.10 osx/homebrew install error still present and only compiled error free with:

make CPPFLAGS=$(pkg-config --cflags freetype2)

**Comment by nioelumijkee** [comment]
there was also a similar problem (although perhaps a completely different one). there were some errors related to FTGL, because of which GEM was assembled without font support. This command helped me: 
```
./configure \
--with-pd=$HOME/local/include/pd \
PKG_FTGL_CFLAGS="$(pkg-config --cflags ftgl freetype2) -std=c++11" \
PKG_FTGL_LIBS="$(pkg-config --libs ftgl freetype2)"
```
 -std=c++11
maybe because of the old version of FTGL ...

**Comment by umlaeute** [comment]
for what it is worth:
Gem is now built on a CI that fetches `ftgl` via brew.sh, and i haven't encountered any (ftgl-related) build problems in the last years.

i'm thus closing this as "fixed otherwhere"
