### ISSUE TITLE
frame problem on GEM for Mac

### ISSUE THREAD

**Issue by H-MLim** [umlaeute/Gem#284]
https://www.facebook.com/groups/puredata/posts/10158996102899495/
(also sorry for replacing FB link because of size of a video)

hello, here's other issue on Mac...when I try to move images, it moves with pretty dropped frames. But when I move my mouse cursor, the frame suddenly rose. And dropped again when hands off from my mouse (this happens too in video file). I have not experienced like this on Windows too, but somebody knows what's the problem? I'm using MacOS Monterey ver. 12.0.1, Pd ver 0.51.4, Gem ver 0.94 and also changed my gem window into [gemglutwindow] from [gemmacoswindow] because of critical recognization problem.

**Comment by umlaeute** [comment]
you have to turn on debug mode for `[gemglutwindow]`.

unfortunately i have forgotten how to do that.
iirc something like this:
- make the Gem window active
- navigate the menu bar
- find the properties
- check the "debug" checkbox

please do not post facebook videos (i won't head to facebook just to see a video).
either you manage to reduce it's size so you can upload it into the ticket description, or you just need to be specific with your project description.
