### ISSUE TITLE
[pix_data]'s gemlist output is inactive

### ISSUE THREAD

**Issue by jamshark70** [umlaeute/Gem#286]
In this screenshot, note:

1. [pix_data] help claims that the leftmost outlet will pass the gemlist through to the next object.
2. My test patch should pass the gemlist to a [print gl-out], so each rendering cycle should print a line like "gl-out: gem_state (pointer) (pointer)."
3. The Pd window prints the gray color value, but there is no printed output from gl-out.

The two possibilities are: [pix_data] was never supposed to output the gemlist and the help file is wrong, or [pix_data] suffered some code rot and accidentally removed the gemlist output.

It's easy to work around -- [pix_data] basically requires a [t] input anyway, so it's easy to do [t a b a] instead of [t b a] and get the downstream gemlist from the trigger's leftmost outlet. But you won't think to do that at first, if the help patch is misleading.

![pd-pix-data](https://user-images.githubusercontent.com/318301/146345374-e0371cd2-f7e1-40d7-86ca-b148be297001.png)

**Comment by umlaeute** [comment]
good point.
i've checked the git history, and there's nothing obvious that would explain the discrepancy.

however, from an interface perspective, i think it would be better to *not* output the gemlist:
the `[bang(` to the first inlet might appear at any time, even if there is no openGL context established (or the wrong one is current), so I'd rather not send a gemlist *then*.
but sending the gemlist when some data goes to the 2nd (typically: cold) inlet *and* there is a first inlet that is *banged* to trigger some action, smells very wrong either.

so i think, the way forward is to just document that this is a "dead outlet (for legacy reasons)".

**Comment by jamshark70** [comment]
﻿> so i think, the way forward is to just document that this is a "dead outlet (for legacy reasons)".


Sure, that makes sense. As long as the documentation matches the real behavior, I'm fine with it 👍
