### ISSUE TITLE
0.94: Can't build due to use of "error()"

### ISSUE THREAD

**Issue by dvzrv** [umlaeute/Gem#287]
Hi! I'm currently trying to rebuild the pd-gem package on Arch Linux.

Unfortunately I am unable to build due to (many of):

```
Event.cpp: In function ‘void dequeueEvents()’:
Event.cpp:353:5: error: ‘error’ was not declared in this scope; did you mean ‘perror’?
  353 |     error("dequeue NULL queue");
      |     ^~~~~
      |     perror
Event.cpp:358:5: error: ‘error’ was not declared in this scope; did you mean ‘perror’?
  358 |     error("dequeue empty queue");
      |     ^~~~~
      |     perror
make[4]: *** [Makefile:816: libGem_la-Event.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
```

Full build log: 
[pd-gem-0.94-build.log](https://github.com/umlaeute/Gem/files/7941893/pd-gem-0.94-build.log)

It seems there have been some fixes for this in
https://github.com/umlaeute/Gem/commit/9025b90e9c5e7894c1472571d5fc05c3614e228f
https://github.com/umlaeute/Gem/commit/072ad46d71ac45b0a2f3ca3f9bee1f9f0fe93d0e
https://github.com/umlaeute/Gem/commit/43622cecd2ddf2204a66a179325659f6a090bb57

Unfortunately those commits do not apply cleanly on top of 0.94. As that version is from two years ago, would it be possible for you to create a new release?

**Comment by umlaeute** [comment]
good point.

in the meantime you can use the patch i'm using for the Debian packaging: https://salsa.debian.org/multimedia-team/pd/gem/-/blob/master/debian/patches/pd_error.patch

**Comment by dvzrv** [comment]
> good point.

Cool, looking forward! :)

> in the meantime you can use the patch i'm using for the Debian packaging: https://salsa.debian.org/multimedia-team/pd/gem/-/blob/master/debian/patches/pd_error.patch

Thanks! I grabbed that one for the time being! :)
