### ISSUE TITLE
pix_mask hangs Pd when dynamically building a masking image

### ISSUE THREAD

**Issue by jamshark70** [umlaeute/Gem#289]
The pictured/attached patch consistently hangs Pd (requires force quit).

If I delete the noted connection, then it doesn't hang, but then there is no masking.

If I bypass pix_mask and display the pix_buffer_read result directly in pix_texture, then the mask image does contain a square (but the positioning seems to be centered on the lower left corner, haven't cracked that problem yet).

The desired behavior is that I should be able to position a square/rectangle/other shape, and pass through the image pixels only within the shape. I didn't quite expect it to be so difficult... 1/ how to draw a shape in a pix (it's possible! but this is not something one would guess -- and coordinating the snap vs texture positions is tricky at best, not solved here); 2/ have I found a bug? Or is the question rather, how to manage multiple pixes in the same render chain (also not exactly obvious from help patches).

Tbh I'm not certain if this is a bug or usage question... but hangs are a nasty category of problem, so I thought I'd at least raise it. It's suspicious that a lot of it seems fine except feeding it into pix_mask.

![pd-gem-crash](https://user-images.githubusercontent.com/318301/161421118-5e66d9e2-1253-4e24-8e0b-ffee6993d1ce.png)

[image-mask-01.pd.zip](https://github.com/umlaeute/Gem/files/8404166/image-mask-01.pd.zip)

**Comment by jamshark70** [comment]
For the special case of a rectangle, I think I can work around it using pix_sig2pix (a couple of phasors, signal comparators, and [*~]). I did get an initial prototype working just now.

The prototype also demonstrates that [pix_mask] isn't fundamentally broken -- it just doesn't like it when the mask image comes from pix_snap. So, what is different about the pix_snap source? I've used pix_info to check the color space of both images going into pix_mask -- both are 6408.

It would be nice to have a general solution, to make it easy to substitute a circle in place of the rectangular mask.

**Comment by umlaeute** [comment]
i totally agree.
have you checked the orientation?

**Comment by umlaeute** [comment]
hmm, i just tried and cannot really reproduce.

`[pix_resize]` is not really the best solution though. better to use a framebuffer that has the correct size.

this slightly modified version of your patch works fine here...

![image-mask-01 pd](https://user-images.githubusercontent.com/214034/161835780-db6e27f6-099f-40f7-a097-ad22324afbf8.svg)

(for whatever reason pastie.iem.at fails to render this patch as SVG, but [here's the patch](https://pastie.iem.at/view/a2e50e35)

**Comment by jamshark70** [comment]
I see -- thanks for testing.

The chain on the right is something that had been demonstrated to me a couple of years ago (and then cleaned up the rest of the way by myself). It does work without explicitly setting the gemframebuffer dimensions -- pix_snap *should* be the object that determines the pix's size.

But I think the real issue is an interaction between this specific image file and pix_resize.

- If I manually rescale the image to 500x500 and delete the pix_resize, then the technique works as shown, no hang.
- If I use the 500x500 image and (redundantly) reintroduce pix_resize, no hang.
- If I use a different image (exported from GIMP) that is not 500x500, and resize to 500x500, no hang.
- If I use the original image that I was trying to use with pix_resize, then it hangs.

So I suppose the real blame falls on whichever poorly-written jpg library produced the original file. (I suppose there must be a lot of those.)

I'll close it. Thanks for the research!

**Comment by jamshark70** [comment]
Actually it seems to be that the original image was too big. pix_resize is fine on smaller images but (I guess) too slow for a large jpg.

**Comment by umlaeute** [comment]
the format of the data on disk, shouldn't really matter for `[pix_resize]` (as it only sees the raw data, not the compressed one).

what's the dimension of the image?

also, offloading the `[pix_resize]` from the main tree should help:

```
[gemhead]
|
[pix_image]
|
[pix_resize]
|
[pix_buffer_write inbuffer]
```
