### ISSUE TITLE
can't install GEM

### ISSUE THREAD

**Issue by H-MLim** [umlaeute/Gem#291]
hi. I'm installed Pd on my new Mac but no libraries are searched in deken (find externals), nor when I install dek file manually, almost all objects are not recognized although I set all the directories and startup flags(at this time, I could load few objects such as gemwin but it doesn't work with error messages on the console). could you let me know how should I do? I'm now working on MacOS Monterey ver 12.1 with Apple M1 Pro., Pd 0.52.2. thanks

<img width="634" alt="스크린샷 2022-04-23 19 41 57" src="https://user-images.githubusercontent.com/68152553/164891192-ac170ade-7e1c-4b21-8763-454cf6bb497a.png">

**Comment by umlaeute** [comment]
the architectures between Pd (arm64) and Gem (x86_64, aka amd64) mismatch - and an arm64 applications cannot load an x86_64 library.

you have two options:
1. run Pd in x86_64 mode via Rosetta (e.g. following [this blog](https://eclecticlight.co/2021/01/22/running-intel-code-on-your-m1-mac-rosetta-2-and-oah/) - note that i haven't verified whether this is the best/authoritative answer, but something along these lines)
2. install a Gem for arm64, see https://github.com/umlaeute/Gem/issues/257#issuecomment-1054713780
