### ISSUE TITLE
Macbook Air M1 Chip Issue

### ISSUE THREAD

**Issue by franklinmck** [umlaeute/Gem#293]
Hi, 
I'm currently working on a Macbook Air (M1 Chip) running Monterey. Gem loads in pd, but when i try to run the examples, I get the following error: 

```
/Documents/Pd/externals/gem/gem.pd_darwin: dlopen(/Users//Documents/Pd/externals/gem/gem.pd_darwin, 0x000A): tried: '/Users//Documents/Pd/externals/gem/gem.pd_darwin' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/gem.pd_darwin' (no such file),
```

are there any workarounds to this?

**Comment by umlaeute** [comment]
>  Gem loads in pd,

i don't see how it does.

in any case there are two possibilities:
- run Pd in Rosetta as an Intel/64bit
- install an experimental arm64 build of Gem, see https://github.com/umlaeute/Gem/issues/257#issuecomment-1055351656

**Comment by umlaeute** [comment]
closing this, as it apparently now works.
