### ISSUE TITLE
[dimen( no working with [pix_video]

### ISSUE THREAD

**Issue by H-MLim** [umlaeute/Gem#298]
![image](https://user-images.githubusercontent.com/68152553/173344331-21037aee-4ebd-46f5-88c2-15622a0d6c69.png)

sorry if I was just misunderstanding, but I'm seeking for changing screen size without changing video resolution from `[pix_video]`. but it seems changing `[rectangle]` forces to change camera resolution together, and `[dimen(` - `[pix_video]` doesn't work...(nothing happens. but originally it changes the resolution of video size right?) assuming from the help file, there should be some messages for `[pix_video]` size but what should it be if `[dimen(` doesn't work?

it's from Windows 10 (ver.21H2, build 19044.1706) with Pd 0.52.2, GEM 0.94, but also on M1 Mac Monterey version 12.4 (with same version of Pd+Gem) has same problem

**Comment by umlaeute** [comment]
from the help-patch of ´[pix_video]`:
> Inlet 1: dimen <number> <number>: set various dimensions for the image (does not work on all capture devices)

what Gem does is request the capture device to capture at a given resolution. if the capture device honors the resolution request, you get what you asked for. if it doesn't, then no resizing is attempted.

now `[rectangle]` (like other Geos) doesn't do *anything* to the resolution of the incoming pixel data. what it does instead, is applying the entire pixel data onto the object: so if the aspect ratio of the rectangle does not match the aspect ratio of the pixes, you get the distortion you are experiencing.

if you want to crop the image, check out `[pix_coordinate]` (or `[pix_crop]`).
in general `[pix_coordinate]` is preferred (as the cropping is done on the GPU), but if you have very large footage (e.g. 8k frames) and you are cropping a considerable amount of data, then `[pix_crop]` might save you some cycles when transferring the data between CPU and GPU memory.

**Comment by H-MLim** [comment]
ah, now I understand. many thanks for your help!
