### ISSUE TITLE
Transparency in webm videos not used

### ISSUE THREAD

**Issue by hellocatfood** [umlaeute/Gem#301]
Following on from #239 I've discovered that GEM can play webm files but if they have transparency this isn't respected. For example, using the following transparent pngs

[frames.zip](https://github.com/umlaeute/Gem/files/9263511/frames.zip)

I encoded this transparent vp9 webm video

[video_vp9.webm](https://user-images.githubusercontent.com/151947/182957178-5090c1ac-fe17-43dd-995c-3766d2f58f9d.webm)

[video_vp9.webm](https://user-images.githubusercontent.com/151947/182956696-18b04104-21eb-429b-8da1-681598a5d6c9.webm)
`ffmpeg -f image2 -i image_%03d.png -c:v libvpx-vp9 -pix_fmt yuva420p video_vp9.webm`

In this patch I tried opening the video and changing the `gemwin` colour.

![Screenshot from 2022-08-04 22-35-17](https://user-images.githubusercontent.com/151947/182957208-d1a5fa53-1c3e-45a4-9992-1b1c1f4e7413.png)

However the alpha channel in the video isn't being used.

I'm using GEM 0.94-7 with 0.52.1  on Ubuntu 22.04

**Comment by umlaeute** [comment]
i can reproduce this.

i guess the problem is that the gmerlin-backend (using libgmerlin-avdec) doesn't properly provide the alpha channel (but it's hard to test, as gmerlin itself - unlike Gem - segfaults with the video)

**Comment by hellocatfood** [comment]
I tried playing the video using `gmerlin-play` and it plays fine. I just get a bunch of messages like this
```
no more csLADSPA plugins
Setting audio stream 0
Setting subtitle stream -1
[matroska] Skipping 1 (1) bytes of element 53c0 in video
[matroska] Skipping 1 (1) bytes of element 53c0 in video
[matroska] Skipping 1512 (5e8) bytes of element 75a1 in block group
[matroska] Skipping 1512 (5e8) bytes of element 75a1 in block group
[matroska] Skipping 89 (59) bytes of element 75a1 in block group
[matroska] Skipping 89 (59) bytes of element 75a1 in block group
[matroska] Skipping 90 (5a) bytes of element 75a1 in block group
[matroska] Skipping 90 (5a) bytes of element 75a1 in block group
[video] Got initial video timestamp: 0
[player] Opening location: 182956696-18b04104-21eb-429b-8da1-681598a5d6c9.webm
[matroska] Skipping 1 (1) bytes of element 53c0 in video
[matroska] Skipping 1 (1) bytes of element 53c0 in video
[matroska] Skipping 1512 (5e8) bytes of element 75a1 in block group
[matroska] Skipping 1512 (5e8) bytes of element 75a1 in block group
[matroska] Skipping 89 (59) bytes of element 75a1 in block group
[matroska] Skipping 89 (59) bytes of element 75a1 in block group
[matroska] Skipping 90 (5a) bytes of element 75a1 in block group
[matroska] Skipping 90 (5a) bytes of element 75a1 in block group
[video] Got initial video timestamp: 0
[matroska] Skipping 1512 (5e8) bytes of element 75a1 in block group
[matroska] Skipping 1512 (5e8) bytes of element 75a1 in block group
[matroska] Skipping 89 (59) bytes of element 75a1 in block group
[matroska] Skipping 89 (59) bytes of element 75a1 in block group
[matroska] Skipping 90 (5a) bytes of element 75a1 in block group
[matroska] Skipping 90 (5a) bytes of element 75a1 in block group
[       0:00 ]/[       0:00 ][xv] Using XV format: YV12
[ov] Using software overlay for stream 0
[matroska] Skipping 128 (80) bytes of element 75a1 in block group
[matroska] Skipping 128 (80) bytes of element 75a1 in block group
Playing audio stream -1
Playing video stream 0
Playing subtitle stream -1
[       0:00 ]/[       0:05 ][matroska] Skipping 191 (bf) bytes of element 75a1 in block group
[matroska] Skipping 191 (bf) bytes of element 75a1 in block group
[matroska] Skipping 222 (de) bytes of element 75a1 in block group
```

I'm using gmerlin 2.0.0~svn6298~dfsg0-1

**Comment by umlaeute** [comment]
i can however confirm, that in OBS the `video_vp9.webm` does indeed have transparency.

**Comment by umlaeute** [comment]
i think i found the problem here: the default codec `vp9` will happily ignore the alpha channel, it's only the `libvpx-vp9` codec that can deal with it. the latter is an optional feature of ffmpeg, so the fix now is to check whether it's available if `vp9` is detected...

it also seems that the webm file is not seekable (so the `filmFFMPEG` backend will not report the EOF and just ignore any frame-change (and instead auto-proceed to the next frame)
