### ISSUE TITLE
[gemwin] Still not working after workaround by issue #257

### ISSUE THREAD

**Issue by EntroSanity** [umlaeute/Gem#304]
I was getting similar problems when creating gem windows on my M1 Mac and Pd-0.51.1. Managed to resolve it with replacing the [gemmacoswindow] with [gemglfw3window], however, when I tested again with [create] [gemwin], there was simply no responses and by clicking the create again, it said the window is already made. I'm quite confused by the issue and any help is appreciated!

**Comment by 60-hz** [comment]
It'a a known issue, and you can find a simple fix here https://github.com/umlaeute/Gem/issues/243#issue-585529890

As this issue rise often in many places, along with the [gemglfw3window] replacement issue, would be great to find a way to provide a new MacOS binary in deken.

**Comment by umlaeute** [comment]
closing as duplicate.

and yes, we should have a new release
