### ISSUE TITLE
[gemglfw3window] draw nothing in single buffering

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#305]
Nothing is drawn with [gemglfw3window] using [buffer 1( message in gemwin-help files in OSX.

Tested from a fresh compiled Gem and the deken version on different computer:
- Macbook M1 with Monterey
- Imac Intel with Mojave

Works fine in Windows.

**Comment by umlaeute** [comment]
> Works fine in Windows.

with `[gemglfw3window]`? (or the default?)

**Comment by 60-hz** [comment]
Yes, with [gemglfw3window].

**Comment by umlaeute** [comment]
what i meant was: does it work with `[gemglfw3window]` on Windows, or are you using the default `[gemw32window]` on this platform?

**Comment by 60-hz** [comment]
Oh sorry, it works with [gemw32window] and it doesn't work with [gemglfw3window]. I tried with the 0.94 Deken package only.
