### ISSUE TITLE
[pix_frei0r] ARGB vs RGBA

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#306]
[pix_frei0r] seems to have wrong rgba channels in OSX (seems to be ARGB instead of RGBA ?).

Tested from a fresh compiled Gem and the deken version on different computer:
Macbook M1 with Monterey
Imac Intel with Mojave

Color are correct in Windows.

**Comment by 60-hz** [comment]
Here is a simple test with this source image:

<img src="https://user-images.githubusercontent.com/5449719/194518067-6825ce6a-400c-44c4-b5e6-75c1b019487e.jpg" width="250" height="250">

With the simple "invert" color plugin with pix_frei0r, Gem display:

<img src="https://user-images.githubusercontent.com/5449719/194519077-715f9f41-f9e9-400c-a128-a003b1336188.png" width="250" height="250">

Should be:
<img src="https://user-images.githubusercontent.com/5449719/194519217-50f80aff-6f27-4964-896a-53ccc6c5a389.jpg" width="250" height="250">

**Comment by umlaeute** [comment]
does this mean, that colors would be wrong when passing them through a trivial pass-thru frei0r-plugin?

(depending on the actual colorspace), Gem does some colorspace conversion before sending the data into the frei0r plugin, and another one on the data returned by the plugin. it seems that one of the two conversions does something wrong).

does it help, if you force the input data to YUV resp RGBA (`[pix_yuv]`, `[pix_rgba]`) **before** the frei0r-plugin?

and as a quick workaround, you should be able to use `[pix_colormatrix]` to get the color channels right again (at least in RGBA mode)

**Comment by 60-hz** [comment]
>does this mean, that colors would be wrong when passing them through a trivial pass-thru frei0r-plugin?

Color are ok until a plugin is loaded in [pix_frei0r].

> does it help, if you force the input data to YUV resp RGBA ([pix_yuv], [pix_rgba]) before the frei0r-plugin?

Same result when using [pix_rgba] before [pix_frei0r], using [pix_yuv] instead returns "[pix_frei0r]: cannot handle YUV image".

Trying to swap channel with [pix_colormatrix] didn't help: when I send "0 0 0 0 0 0 0 0 0" color matrix to [pix_colormatrix], I have full yellow instead of white (since I use the invert color plugin...).

**Comment by umlaeute** [comment]
you should usea 4x4 matrix for swapping the colors

**Comment by 60-hz** [comment]
I tried with different colors that I found here https://frei0r.dyne.org/codedoc/html/group___c_o_l_o_r___m_o_d_e_l.html
I tried before and after [pix_frei0r] but still, I cannot get the color right...

<img width="467" alt="Capture d’écran 2022-10-13 à 17 57 06" src="https://user-images.githubusercontent.com/5449719/195646352-d7a5d0a5-4d43-4b4d-a1ed-f769a4cc701e.png">


Note1: [open( message that is in the help file is wrong, I need to use [load(
Note2: the toggle is very handy to bypass the effect, like the other pix_object but it's not mentioned in help.

**Comment by umlaeute** [comment]
so just to be sure: it is broken on both M1/arm64 and macintel/amd64?

**Comment by 60-hz** [comment]
Yes, same result in intel machine. I forgot to add [alpha], but it looks like one channel is missing.

**Comment by umlaeute** [comment]
actually it's just byteswapping that is missing... (it's `RGBA` vs `ABGR`)

**Comment by 60-hz** [comment]
Not sure, sending ABGR list [0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0( to [pix_colormatrix] before [pix_frei0r] gives this:
<img alt="ABGR" src="https://user-images.githubusercontent.com/5449719/198297189-5c262c9b-2624-413a-8e1f-c83d12bc72c7.png" width="250" height="250">

Also, if I send black list  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0(  before frei0r gives all pixels to yellow!

**Comment by 60-hz** [comment]
@umlaeute 
I see you have already attempted to fix it in the current master.
After a quick compilation, I confirm the color are now correct in OSX, thanks!

I cannot help asking: Using [pix_buf 1] is the best way to do to see the result before [pix_frei0r] on a static image? It looks like other pix objects works even without it. (Also I note that pix_buf-help.pd say "none" as argument", but it actually have one to force image-processing).

**Comment by umlaeute** [comment]
fixed the caching with `[pix_frei0r]` (and hopefully with `[pix_freeframe]`)
