### ISSUE TITLE
[ortho] has wrong buffer size

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#307]
Under MacOs, [ortho] draw in lower left corner instead of fullwindow. Might be related to [gemglfw3window] buffer issue https://github.com/umlaeute/Gem/issues/243#issue-585529890

<img width="764" alt="Capture d’écran 2022-09-29 à 11 28 10" src="https://user-images.githubusercontent.com/5449719/192995474-aec69d65-ae42-4a39-9fca-fc6704a1aa82.png">

**Comment by umlaeute** [comment]
should be fixed with bda2c4b89a7785a7bf3eb1f07678e8804ccc8d23

**Comment by umlaeute** [comment]
it would be great if you could test whether this is indeed fixed (and it doesn't even require recompilation :-))

**Comment by 60-hz** [comment]
I just replaced gemwin.pd in my arm compiled Gem and I confirm it is Fixed!

**Comment by umlaeute** [comment]
:tada:
