### ISSUE TITLE
[model3d] texture is flipped

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#311]
Trying different .obj files (downloaded and exported from Blender) with [model] and default OBJ loader: the texture is vertically flipped. (need to use [pix_flip vertical] ). A method for vflip and hflip for [model] would be very handy since texture flipped is often an issue.

Same issue on:
MacOS
Windows10

**Comment by umlaeute** [comment]
could you provide a simple example (model + texture + patch) to demonstrate the problem?
(it's just so much easier to work an an issue if you don't have to build a reproducer first)

**Comment by 60-hz** [comment]
Sure 
[test_model_texture.zip](https://github.com/umlaeute/Gem/files/9902509/test_model_texture.zip)

**Comment by 60-hz** [comment]
This very same example is now crashing pd-0.53-1 on launch.
Removing the .obj file in [model] works with the [open( method

pd-0.53.1 Apple M1 Pro
Gem from last job artifact: https://git.iem.at/pd/Gem/-/jobs/45642

**Comment by umlaeute** [comment]
hmm, doesn't crash here (Debian/GNU linux; assimp-5.2.5); the artifact has been compiled against assimp5.2.0.
and there seem to be [a few bug-fixes](https://github.com/assimp/assimp/releases/tag/v5.2.5) regarding OBJ.

**Comment by umlaeute** [comment]
im not sure i understand the assimp version in the artifact though; the logfiles mention `/usr/local/Cellar/assimp/5.2.0/include` (that's why i assume assimp-5.2.0), but the brew.sh page says it should be [5.2.5](https://formulae.brew.sh/formula/assimp) :thinking:

**Comment by 60-hz** [comment]
I confirm:
The crash happen only on MacOS, when loading obj before windows creation, using [gemglf3window].
I tried on windows also, there is no crash with the same patch (tried with default [gem32window] and also [gemglf3window]...)

I don't think Gem is using assimp loader by default but the default OBJ one.

**Comment by umlaeute** [comment]
> I don't think Gem is using assimp loader by default but the OBJ one?

hmm, well that depends :-P
there's no specific priority assigned to either assimp nor the default OBJ loader.
i guess the priority depends on how the filesystem orders the files...

which might explain the system differences (but then: does it crash if you loadbang `[loader OBJ, open mymodel.obj(` resp `[loader ASSIMP3, open mymodel.obj(` instead of specifying the model as argument?)

**Comment by 60-hz** [comment]
>but then: does it crash if you loadbang [loader OBJ, open mymodel.obj( 

No! So the ASSIMP plugin is loaded by default, and will crash if windows context is not created before... good point!

I really didn't know that assimp would be first loaded, that might explain some weird behaviour I have on same patch on a windows machine compiled without assimp...

**Comment by umlaeute** [comment]
in general ASSIMP is the better and much more powerful modelloader...

**Comment by 60-hz** [comment]
It support more files format, but have less properties (always numread 0, numwrite 3) and they don't do anything, or I didn't get how to use them...

Also, when using ASSIMP loader, I cannot use other useful methods like [group( or [smooth(
