### ISSUE TITLE
Test builds error on MacOS < 11.0

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#314]
Tried the last builds from https://git.iem.at/pd/Gem/-/jobs/ and I worked very well on my M1 with Monterey computer.

But I tried Intel version using MacOS Mojave, Gem load ok but [gemglfw3window] cannot be create and return this error:

```
/Users/username/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin: dlopen(/Users/username/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin, 10): Symbol not found: _OBJC_CLASS_$_NSConstantDictionary
  Referenced from: /Users/username/Documents/Pd/externals/Gem/libglfw.3.dylib (which was built for Mac OS X 11.0)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Users/username/Documents/Pd/externals/Gem/libglfw.3.dylib
/Users/username/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin: dlopen(/Users/username/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin, 10): Symbol not found: _OBJC_CLASS_$_NSConstantDictionary
  Referenced from: /Users/username/Documents/Pd/externals/Gem/libglfw.3.dylib (which was built for Mac OS X 11.0)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Users/username/Documents/Pd/externals/Gem/libglfw.3.dylib
 gemglfw3window
... couldn't create
```

**Comment by 60-hz** [comment]
Ok, simply replacing the file libglfw.3.dylib with my last compiled version works also on my old 10.14.6 now.

**Comment by umlaeute** [comment]
hrmpf.
fixing this is getting tricky, if we want to continue to use libraries from homebrew. (which only supports the last few macOS versions)

**Comment by umlaeute** [comment]
i cannot currently test `[gemglfw3window]` on Catalina (as I only have a VM, and `[gemgflw3window]` cannot create a rendering context in the VM), but even with the latest builds (https://git.iem.at/pd/Gem/-/jobs/50077/artifacts/download), I cannot even *load* `[gemglfw3window]` on on Mojave (as the shipped libglfw3 requires at least Catalina).

i'm not entirely sure whether I should make an effort into getting hold of glfw for Mojave (or older), as there is no support for this OS for a few years now (and the various dependencies are pulled from brew, which has even dropped support for Catalina for now)...

so i'm inclined to tag this as "wontfix" (sorry)

**Comment by umlaeute** [comment]
> I cannot even *load* `[gemglfw3window]` on on Mojave (as the shipped libglfw3 requires at least Catalina).

which incidentally, is what this bug-report is actually about.

however, since i am (well: *was*; i haven't tested recently) able to *load* the `[gemglfw3window]` object on macOS 10.15 (Catalina), i think that this is the minimum required version of macOS (rather than macOS 11 (Big Sur), as indicated in the title).

anyhow, closing this as i don't intend to fix this.
