### ISSUE TITLE
pix_data: pixel position not accurate for large image 

### ISSUE THREAD

**Issue by ch-nry** [umlaeute/Gem#315]
pix_data input accept numbers between 0 and 1 for the colour position to get. Internally, this values are converted to pixel (int) by multiplication with the image size. 
When using large images, the float number precision between 0 and 1 is not accurate enough to distinguish between 2 adjacent pixels. 
It would be nice to add a mode to this object so it accept number between 0 and imagesize-1, better than 0 and 1.

**Comment by umlaeute** [comment]
which sizes are you dealing with?

**Comment by umlaeute** [comment]
hmm, 16k shouldn't really be a problem with regard to floating point precision.

does it happen in the first row of the image, or only later?

**Comment by ch-nry** [comment]
If i's not a precision problem, then it's a bug in my patch!
Sorry for the noise.
But I would still appreciate to have a solution to control pix_data with pixel value.

**Comment by umlaeute** [comment]
> If i's not a precision problem, then it's a bug in my patch!

probably. however, i'm only saying that the 16k range *shouldn't* be a problem. there still might be some unintended overflow happening.

> But I would still appreciate to have a solution to control pix_data with pixel value.

hmm. what for exactly? to save a few CPU-cycles by not performing a useless division (`x/width`) which is then followed by a multiplication that undoes it (`w*width`).

speaking of multiplications: could your problem be related to the fact that `[pix_data]` actually does a `x*width` de-normalisation, instead of `x*(width-1)`?
(I don't know why it is like that)

**Comment by ch-nry** [comment]
> > But I would still appreciate to have a solution to control pix_data with pixel value.
> 
> hmm. what for exactly? to save a few CPU-cycles by not performing a useless division (`x/width`) which is then followed by a multiplication that undoes it (`w*width`).
Not to save cpu, but space and clarity in the patch.
btw, I do a (x+0.5)/width in order to avoid rounding error after the *width multiplication.

> 
> speaking of multiplications: could your problem be related to the fact that `[pix_data]` actually does a `x*width` de-normalisation, instead of `x*(width-1)`? (I don't know why it is like that)
I check the code to get the correct multiplication. The behaviours is indeed strange, since the max is 1-(1/width).
Having a "pixel" mode would keep this odd behaviours, and offer a clean option. (So one do not have to look at the code to check the correct multiplication factor)...

**Comment by ch-nry** [comment]
thanks!
