### ISSUE TITLE
symbol not found in flat namespace macOS

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#317]
Just tested from here:
https://git.iem.at/pd/Gem/-/jobs/43456/artifacts/download

Macbook M1 
Ventura 13.0
pd 0.53.0

In pd console:
/Users/megrimm/Documents/Pd/externals/Gem/Gem.pd_darwin: dlopen(/Users/megrimm/Documents/Pd/externals/Gem/Gem.pd_darwin, 0x000A): symbol not found in flat namespace '__ZN12FTBitmapFontC1EPKc'
Gem: can't load library

I was getting a "Cannot Be Opened Because the Developer Cannot be Verified" when loading library.  Had to "allow" in Privacy & Security.

FYI I have compiled my own a few weeks ago that seems to load fine.

**Comment by umlaeute** [comment]
> I was getting a "Cannot Be Opened Because the Developer Cannot be Verified" when loading library. Had to "allow" in Privacy & Security.

did you allow it for both Gem.pd_linux and ibftgl.2.dylib + libfreetype.6.dylib + libpng16.16.dylib

**Comment by megrimm** [comment]
disabled gatekeeper with:

 `sudo spctl --global-disable`

still the same issue. although now I also get:

`/Users/megrimm/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin: dlopen(/Users/megrimm/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin, 0x000A): symbol not found in flat namespace '__ZN9CPPExtern10m_holdnameE'`

**Comment by umlaeute** [comment]
as of https://git.iem.at/pd/Gem/-/jobs/50077/artifacts/download i cannot reproduce this (`[gemglfw3window]` on macOS12.5.1/Monterey arm64(M1))
