### ISSUE TITLE
[model] width method and documentation

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#329]
[model] returns "model: no method for 'width'".
Also, draw mode line are not documented in model help file, and "width" method is not documented in any geo"s help files (Guess value is from 1 to 15?)

**Comment by umlaeute** [comment]
> Guess value is from 1 to 15?

the values are passed as-is to the openGL-renderer., and are implementation dependent.

**Comment by umlaeute** [comment]
` [model]` now accepts the `[width(` message.

as for documentation: please open separate tickets for separate issues.

in general, i find that repeating the same info over and over again, a bit tedious (both as the one who should put it there, **and** when reading documentation).
however, I understand that right now it is not documented at all, which is even worse.
