### ISSUE TITLE
loading Gem fail with command line

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#330]
Under MacOS, loading a patch containing [declare -lib Gem] with command:

` /Applications/Pd-0.53-1.app/Contents/Resources/bin/pd /Users/.../load_gem.pd`

fail, and returns:

`/Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin: dlopen(/Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin, 0x000A): symbol not found in flat namespace (__ZN12FTBitmapFontC1EPKc)
/Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin: dlopen(/Users/.../Documents/Pd/externals/Gem/Gem.pd_darwin, 0x000A): symbol not found in flat namespace (__ZN12FTBitmapFontC1EPKc)`

Same patch can load ok without using command from terminal.

pd-0.53.1 Apple M1 Pro
Gem artifact: https://git.iem.at/pd/Gem/-/jobs/45616

**Comment by umlaeute** [comment]
the artifacts only ship dependencies for x86_64, you would have to install them manually (with `brew install ftgl`).

this is mainly due to `brew` not allowing/supporting fat binaries.

i have no immediate idea on how to solve this in general (a *vague* idea is to pre-build fat binaries of dependencies and drop brew).

see also #37

**Comment by 60-hz** [comment]
ftgl is already installed on my system, so I was wondering why this message happen only when I launch pd and Gem using command line.

**Comment by umlaeute** [comment]
> ftgl is already installed on my system

for arm64?

> why this message happen only when I launch pd and Gem using command line.

weird indeed.
maybe starting Pd "via the desktop" launches it in rosetta mode?

**Comment by 60-hz** [comment]
> maybe starting Pd "via the desktop" launches it in rosetta mode?

True! I made a rosetta compatible Terminal and it works as expected, sorry for the noise!
Issue closed!
