### ISSUE TITLE
modelASSIMP3 crashes when used before Window has been created

### ISSUE THREAD

**Issue by umlaeute** [umlaeute/Gem#332]
[This very same example](https://github.com/umlaeute/Gem/files/9902509/test_model_texture.zip) is now crashing pd-0.53-1 on launch.
Removing the .obj file in `[model]` works with the `[open(` method

It looks like the model needs to be loaded After windows is created.

pd-0.53.1 Apple M1 Pro
Gem artifact: https://git.iem.at/pd/Gem/-/jobs/45616

_Originally posted by @60-hz in https://github.com/umlaeute/Gem/issues/311#issuecomment-1407639827_

**Comment by umlaeute** [comment]
@60-hz could you confirm that the crash is fixed in recent `master`

**Comment by 60-hz** [comment]
Unfortunately, It's still crashing...

**Comment by umlaeute** [comment]
too bad.
could you somehow create a backtrace?

**Comment by 60-hz** [comment]
Running pd with -verbose and -stderr has only few information... but if there is another solution I might try

```
not reloading 'image' plugins (already 5 loaded)
verbose(4): tried /Users/.../Desktop/Gem_tests/test_model_texture/Rubber_Duck.jpg and succeeded
verbose(4): [pix_image]: loading image '/Users/.../Desktop/Gem_tests/test_model_texture/Rubber_Duck.jpg' with ID:1
not reloading 'model' plugins (already 2 loaded)
zsh: segmentation fault  /Applications/Pd-0.53-1.app/Contents/Resources/bin/pd -verbose -stderr 
```
