### ISSUE TITLE
Framebuffer under MacOS

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#342]
Under MacOS, every Gem jobs after [#47038](https://git.iem.at/pd/Gem/-/jobs/47038) (master d2b7279e ) seems to have wrong framebuffer size again (rendering in lower left corner).

**Comment by umlaeute** [comment]
thanks.

most commits since then have been on the `glad` branch, which considerably changes window management.

just to be sure: does the problem also show on the recent `master` builds?
- https://git.iem.at/pd/Gem/-/jobs/47247
- https://git.iem.at/pd/Gem/-/jobs/47213

**Comment by umlaeute** [comment]
ah, the actual culprit was 628b713abc6818cb631f341fceb2223cea337378
