### ISSUE TITLE
Fullscreen message issues with [gemglfw3window]

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#343]
Using [gemwin] with [gemglfw3window], "fullscreen 1" messages have issues:

- On MacOS it draw only one corner of the screen.
- On Windows the resolution is wrong (gemwin returns "framebuffersize 640 480", need to send "dimen" with correct screen values before creation to be ok), and also... gem is created on screen 2 if present (?) even with "fullscreen 1".

**Comment by umlaeute** [comment]
has this been fixed with https://github.com/umlaeute/Gem/commit/628b713abc6818cb631f341fceb2223cea337378 (as in https://github.com/umlaeute/Gem/issues/342#issuecomment-1534899274)?

**Comment by 60-hz** [comment]
Yes, I confirm the issue is fixed on MacOS system, thanks!
I don't have access to a window machine to try more.
