### ISSUE TITLE
[repeat] abstraction missing

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#344]
The [repeat] abs used in example/13.recursion/02.iteration_is_insufficient is missing.
would be an handy addition also to have a second inlet to set the number of iterations in that abstraction.

**Comment by 60-hz** [comment]
Ok, [repeat] is a zexy dependency in that help file, then it is missing the object [declare -lib zexy].

But could be nice to include it as a gem abstraction.
Here is a simple [repeat] abstraction example using [until] with an help file. [repeat+help.zip](https://github.com/umlaeute/Gem/files/11017126/repeat%2Bhelp.zip)

**Comment by umlaeute** [comment]
thanks.

however adding a `[repeat]` abstraction is not going to fly, as this nameclashes with zexy's `repeat`.

i'm slightly undecided whether we should
- just add `[declare -lib zexy]` to the patch (given that the example explicitly talks about using zexy's `repeat`)
- add a `[gemrepeat]` abstraction that just repeats gemlists (like yours)

**Comment by umlaeute** [comment]
there's also `examples/02.advanced/19.pointer.pd` (ff), which already explains how to use `[until]` + `[gemlist]`

**Comment by 60-hz** [comment]
> however adding a [repeat] abstraction is not going to fly, as this nameclashes with zexy's repeat.

agree.

> add a [gemrepeat] abstraction that just repeats gemlists (like yours)

It sounds interesting since iteration is nice to teach during workshop and  downloading a lib or searching deep into examples/02.advanced/19.pointer.pd is not easy to find for newcomers.
