### ISSUE TITLE
[gemframebuffer] "view" support

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#351]
[gemframebuffer] support "perspec" messages like [gemwin] but don't support the "view" message. I often need this and think it would be a great addition.

**Comment by umlaeute** [comment]
i actually quite like the simplicity of the `[gemframebuffer]` object, which allows you to easily build your own `[view(` message.

e.g.
```
[gemhead]
|
[gemframebuffer]
|
[rotateXYZ 0 <elevation> <azimuth>]
|
[translateXYZ 0 0 -4]
|
```

or (for the 9-args version of the `[view(`):

```
[gemhead]
|
[gemframebuffer]
|
[GEMgluLookAt 0 0 4  0 0 0  0 1 0]
|
```
