### ISSUE TITLE
Latest Linux release?

### ISSUE THREAD

**Issue by jamshark70** [umlaeute/Gem#358]
I just encountered a strange crash in a Gem patch.

However, I'm not certain that I'm running a very recent Gem. If my Gem is out of date, then there's no point in logging a bug for that.

For some strange reason, when I [declare -lib Gem], it prints *nothing* in the console window. In every other system where I installed Pd+Gem, it would always print an extensive preamble, including version, image plug-ins, etc. In this system, it isn't doing that at all.

I look at README.txt and, quite surprisingly, at the top I see only "This is GEM - Graphics Environment for Multimedia," and no indication of the current version anywhere else.

If I search deken for Gem, I get: "Gem-v0.0.extended-(Linux-i386-32)(Linux-amd64-64)-externals.tar.gz
	Uploaded by chr15m @ 2015-08-07 14:36:01"

2015? Why... that can't be right.

The upshot is... today in class, on a Windows machine, I built a demo patch of iterative drawing, and it worked perfectly fine. I run the same patch on my Linux machine, and it crashes. So I'd like to have some way to be sure that I'm running an up-to-date Gem, but I find myself lacking critical information for that purpose.

**Comment by jamshark70** [comment]
FWIW -- the crash does not occur in Gem built from sources.

So the entire problem seems to be that deken, rather curiously, is stuck on an 8-year-old version of Gem (and I unwittingly thought that installing from deken would be less trouble).

**Comment by umlaeute** [comment]
> 2015? Why... that can't be right.

yes.
there are no Gem binaries for linux on deken (well: there shouldn't be any).
use your distribution's package manager to install Gem (and if it is lacking such a package, you need to compile it manually).

the reason is, that Gem has a large number of dependencies and your average linux distribution has everything needed to satisfy the dependencies. i do not plan to make any linux uploads to deken.

**Comment by jamshark70** [comment]
> well: there shouldn't be any

There's at least one, from 2015. I wonder whom to petition to have outdated packages removed.

This is certain to mislead people, as it misled me.
