### ISSUE TITLE
[pix_sig2pix~] inverted channels

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#370]
[pix_sig2pix~] : the first and third channels are inverted (is "blue green red" instead of "red green blue", as stated in the help file). (Tested on MacOS 12.6, M1)

**Comment by umlaeute** [comment]
thanks, i've heard the same from a student.

**Comment by umlaeute** [comment]
can you check whether it's also reverted on macOS/intel?

**Comment by umlaeute** [comment]
got my hands on our M1 (macOS 12.6.7), and can confirm that the problem exists on both M1 and Intel
