### ISSUE TITLE
[pix_invert] issues

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#374]
With latest deken snapshot, pix_invert is not doing anything with rgba images on MacOS.
pix_invert still works with grey/yuv images.

**Comment by umlaeute** [comment]
what is the exact colourspace (as reported by `[pix_info]`)?

**Comment by umlaeute** [comment]
so i just tested on macOS/Sierra(10.12.6) - obviously amd64 - and i couldn't find any problems with any of the three main colorspaces.

the image source is `[pix_video]`, which outputs as default an rgba imag (`GL_BGRA`).
inserting `[pix_rgba]`, `[pix_yuv]` or `[pix_grey]` between the video-object and `[pix_invert]` always produces the correct result.

**Comment by umlaeute** [comment]
i noticed though, that there's some conversion issue, when converting from YUV  to RGBA, but that's a separate issue...

**Comment by 60-hz** [comment]
colorspace reported by pix_infos is "32993", which is supposed to be "GL_BGRA" I guess.

I confirm the issue with pix_video and pix_image with help files on MacOS 12.6

**Comment by umlaeute** [comment]
in the meantime i was able to reproduce

**Comment by umlaeute** [comment]
fixed in f1056d4e1e9596f83b9cbe4ec67c4d1052b776e5
