### ISSUE TITLE
libftgl not Found

### ISSUE THREAD

**Issue by charlesneimog** [umlaeute/Gem#381]
Hi, I am on Fedora. And I have this error:

```
/home/neimog/Documents/Pd/externals/Gem/Gem.pd_linux:libftgl.so.2: cannot open shared object file: No such file or directory
```

gem version: `0.94`;
Fedora 38;
Pd 0.54

**Comment by umlaeute** [comment]
you have to manually install ftgl.

the deken package for Linux (i assume you've installed via deken, as you haven't indicated otherwise) does not come with any dependencies, so you have to install them yourself.

to quote from the README that is shown when installing Gem via deken:

> ### LINUX users
> please note that while we do provide downloadable pre-compiled binaries via deken, these do not include any dependencies, so are unlikely to run out-of-the box.
> 
> instead, we suggest installing Gem via your distribution's package manager (which might install just enough dependencies to *also* get the snapshot to work).
> 
> in general, we suggest to compile Gem yourself: https://git.iem.at/pd/Gem

**Comment by charlesneimog** [comment]
thanks!

**Comment by charlesneimog** [comment]
On Fedora:

```
sudo dnf install libndi-sdk ftgl glfw

```

at least for me now...

**Comment by umlaeute** [comment]
well, the packages you need to install depend heavily on the packages that are already installed. i can think of at least a handful of additional packages that are missing from your list to get all the features from the binaries.

otoh, if you only need core functionality, then you certainly do *not* need `libndi-sdk`.

anyhow, your input is appreciated (and will hopefully help future fedora users)
