### ISSUE TITLE
NDI decklink: unable to initialize framework

### ISSUE THREAD

**Issue by unerds** [umlaeute/Gem#382]
hi folks, i'm just getting started with Gem here. forgive my ignorance, please.

having this issue which I believe is resulting in me being unable to actually create gemwin window

console output is: `NDI SDK APPLE 18:52:30 Jul 26 2023 5.6.0
cannot use record plugin 'decklink': DeckLink: unable to initialize Framework`

this output is duplicated for video plugin.

PD ver: 0.54.0 (darwin 64)
gemwin - latest from pd externals browser (0.94 snapshot?)
macos ventura (13.4)
2020 macbook pro (intel / intel iris plus)

now, i do work in video and am aware of a hardware component called "decklink" by blackmagic design, is that a requirement?

could someone point me in the right direction, perhaps?

when I attempt to actually create the a gemwin window it does nothing.  the create command does nothing.  as i understand it, executing the create command (attached to gemwin message) should actually create a window, yeah?

**Comment by umlaeute** [comment]
1. the `NDI` error is really just a warning. Gem ships with various plugins, among them capture/output plugins for the BlackMagick Decklink cards. When Gem is started, it attempts to initialize all found plugins (e.g. to give a list of which plugins are actually there). as a side-effect of initializing the plugins, there might be some output generated. in any case, as long as you do not want to use the NDI plugins (which obviously do require the Decklink hardware, *and* the driver framework from Blackmagic), you can safely ignore this message
2. as for not being able to create a window: you probably should start with the example patches. if it still does not work, please open a (new) ticket here, including the full output of the Pd-console (and possibly the stdout/stderr as well)
