### ISSUE TITLE
Error message when i type [gemwin] on MacOS

### ISSUE THREAD

**Issue by Dixi385** [umlaeute/Gem#385]
Hi, i'm new with Gem. I've just downloaded the library and i receive this error message when i type [gemiwin] command :
Users/"MyName"/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin:dlopen(/Users/"MyName"/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin, 10): Symbol not found: _objc_opt_class
  Referenced from: /Users/"MyName"/Documents/Pd/externals/Gem/libglfw.3.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
 in /Users/"MyName"/Documents/Pd/externals/Gem/libglfw.3.dylib
/Users/"MyName"/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin:dlopen(/Users/"MyName"/Documents/Pd/externals/Gem/gemglfw3window.pd_darwin, 10): Symbol not found: _objc_opt_class
  Referenced from: /Users/"MyName"/Documents/Pd/externals/Gem/libglfw.3.dylib **(which was built for Mac OS X 10.15)**
  Expected in: /usr/lib/libobjc.A.dylib
 in /Users/"MyName"/Documents/Pd/externals/Gem/libglfw.3.dylib

1. . I'm running **Pd 0.54.0**
2. My Mac version : **Mojave 10.14.6** (could that be the problem?)*

*i have to update my mac? or i have to install an older version of Gem?

**Comment by umlaeute** [comment]
I try to get keep as backwards-compatible as possible, but Apple is making this very hard.

So yes, i think you ought to upgrade to macOS 10.15 (Catalina) (but make backups and everything).
