### ISSUE TITLE
[pix_snap] issue under MacOS

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#387]
[pix_snap] displays a black image under MacOs (M1, Sonoma 14.0).
Here is the print in the help file:
` [pix_snap]: type: 32821 (32821)`

 [pix_snap2tex] works on the same machine...

[pix_snap] is working under windows10, with a different type printed in the help file:
`[pix_snap]: type: 5121 (5121)`

**Comment by umlaeute** [comment]
I cannot reproduce this (M1, Ventura 13.6.1).

The help-patch for `pix_snap` works fine (well kind-of: the `[pix_invert]` seems to be not doing anything with the default RGBA-mode on Apple (which is `GL_BGRA`), but apart from that it does correctly create snapshots).

i've also run the `tests/manual/pix-writing` test (something like `tests/manual/plugintest.sh tests/manual/pix-writing/MAIN.pd image`) and it produces correct images of snapshots.

the *type* is `GL_UNSIGNED_BYTE` on Windows and `GL_UNSIGNED_INT_8_8_8_8` on Apple (which is what we are using for YUV on Apple; i'm not exactly sure whether we want to use the same type for RGBA as well, but chances are that this shouldn'tg be a problem).

**Comment by umlaeute** [comment]
> The help-patch for pix_snap works fine (well kind-of: the [pix_invert] seems to be not doing anything with the default RGBA-mode on Apple (which is GL_BGRA), but apart from that it does correctly create snapshots).

this part is of course a duplicate of #374

**Comment by 60-hz** [comment]
It works now in the last deken version so closing it.
