### ISSUE TITLE
cannot download GEM with deken

### ISSUE THREAD

**Issue by H-MLim** [umlaeute/Gem#393]
![image](https://github.com/umlaeute/Gem/assets/68152553/80ac460e-ad5e-4dae-b833-0e7fa0191ad8)

hi. I couldn't download the recent GEM while downloading through deken, with the error message like "failed to confirm SHA256 of C:/Users/(username)/Documents/Pd/externals/Gem[0.94-snapshot].0.dek". what would be problem? I'm in Pd version 0.54.1, Windows 11

**Comment by H-MLim** [comment]
oh, I found this is the whole problem of deken. I'll re-report on Pd or deken github.

**Comment by umlaeute** [comment]
with my deken-maintainer hat on: yes, sorry for the inconvenience.

there's some instructions on how to install a new deken that allows you to install packages again: https://github.com/pure-data/deken/issues/299#issuecomment-1867665550
