### ISSUE TITLE
PD's not able to create GEM objects

### ISSUE THREAD

**Issue by Kendall555** [umlaeute/Gem#409]
Hello there,

So yesterday, I installed GEM on MAC OS Monterey 12.6 and it was working fine. Today I reopened the project that I've tried it on and found that none of the GEM objects that I've added were recognised by PD and my log was full of "... couldn't create" errors. I've tried reinstalling Gem and loading some of the help patches from the Gem folder in the externals but I got the same result.
 Attaching a screenshot below and looking forward to any suggestions! Thank you! 
<img width="1280" alt="Screenshot 2024-01-17 at 18 37 27" src="https://github.com/umlaeute/Gem/assets/156949381/1e3a4e68-6f5d-4696-82ff-f67fbfa9403f">

**Comment by umlaeute** [comment]
- you probably shouldn't call your patch "GEM" (it might lead to a name-conflict with the ´[Gem]` object (macOS' HFS+ is case-insensitive)
- where did you install Gem?
- what do you get when loading Gem? (Gem prints a nice boilerplate message to the Pd-console; if you don't see it, something went very wrong)
- track the loading by raising verbosity (first switch the Log-level selector to  `4 - all`; then run pd in `-verbose` mode (change via the startup preferences, and restart)

**Comment by Kendall555** [comment]
> * you probably shouldn't call your patch "GEM" (it might lead to a name-conflict with the ´[Gem]` object (macOS' HFS+ is case-insensitive)
I've also tried creating GEM objects in a new patch and was getting the same error messages. And I tried renaming the patch in the screenshot with no result. 
> * where did you install Gem?
In Documents/Pd/externals/Gem
> * what do you get when loading Gem? (Gem prints a nice boilerplate message to the Pd-console; if you don't see it, something went very wrong)
If you mean when doing [declare -lib Gem], than yes I get nothing. 
> * track the loading by raising verbosity (first switch the Log-level selector to  `4 - all`; then run pd in `-verbose` mode (change via the startup preferences, and restart)
I did that, but it I'm not sure what to make of it, but it just looks like Pd and failing to create to objects. Sorry,  I'm fairly new with this type of work! That's a screen recording of what I'm getting: https://youtu.be/7_V7O8qcRT0

I guess what's also strange that it was working totally fine yesterday, then I closed the patched and when I opened it today it was like this, so I'm not sure what could have changed. 

Also, I downloaded/installed it via the Help/Find Extensions in Pd and it said that it's not a release version but a snapshot of the current build. Do you think that could have anything to do with it?  

Thank you for the help!

**Comment by umlaeute** [comment]
instead of a screen recording, please do the following:
- in the Pd-console go to <kbd>File</kbd>-><kbd>Save As...</kbd>
- enter some name like "pdgem.log" and hit <kbd>Enter</kbd>
  - this will save all the messages to a text-file
- then attach this text-file to the issue tracker (or paste it)

it's super-simple to find words in text. it's super-complicated to do the same in a video.

**Comment by Kendall555** [comment]
I though there must a way to do that! 

[pdgem.txt](https://github.com/umlaeute/Gem/files/13969377/pdgem.txt)

**Comment by umlaeute** [comment]
your logfiles shows that the file `/Users/dovydasgataveckas/Documents/Pd/externals/Gem/Gem.pd_darwin` cannot be found.
check whether the file is there.
if it is not, somebody has removed it.

**Comment by Kendall555** [comment]
That's odd because I'm the only one who has access to this computer and I've tried deleting and reinstalling the library multiple times so I guess that file should have been written back into the externals folder. What do you suggest I do?

**Comment by umlaeute** [comment]
1. check whether the files are indeed missing
2. check whether they are automatically deleted by your OS
3. find out why (and how you can prevent this)

**Comment by Kendall555** [comment]
I deleted and reinstalled the library and it worked for single  instance again and then I’m just getting the same error. 

I really have no idea how to check if my OS is deleting it automatically.. 

I’m thinking whether this could be happening because of me installing a snapshot release of the latest build? And if there’s a different way of installing a more stable release? If so how would I go about doing that?

**Comment by umlaeute** [comment]
> I really have no idea how to check if my OS is deleting it automatically..

me neither (hey, it's *your* OS :-))

> I’m thinking whether this could be happening because of me installing a snapshot release of the latest build? And if there’s a different way of installing a more stable release? If so how would I go about doing that?

no not really.
the snapshot releases should be better in every regard, as they are (or well: should be) signed and notarized.

could you verify the signatures of all the binaries, by running something like the following within the Gem folder (while the files are still there):

```sh
codesign -dv --verbose *.pd_darwin
codesign -dv --verbose *.d_fat
codesign -dv --verbose *.so
codesign -dv --verbose *.dylib
```

and post the output to each command (as text)?

**Comment by Kendall555** [comment]
Sorry! I'm super new to this, thank for your patience and help! 

I hope I did this correctly: 

Dovydass-MBP:~ dovydasgataveckas$ codesign -dv --verbose=4 /Users/dovydasgataveckas/Documents/Pd/externals/Gem/Gem/Gem.pd_darwin
Executable=/Users/dovydasgataveckas/Documents/Pd/externals/Gem/Gem/Gem.pd_darwin
Identifier=Gem
Format=Mach-O universal (x86_64 arm64)
CodeDirectory v=20400 size=46663 flags=0x0(none) hashes=1453+2 location=embedded
VersionPlatform=1
VersionMin=657664
VersionSDK=787200
Hash type=sha256 size=32
CandidateCDHash sha1=9bfdd51124fb1b481b77256391d2ff0e94ea6796
CandidateCDHashFull sha1=9bfdd51124fb1b481b77256391d2ff0e94ea6796
CandidateCDHash sha256=c5e445b7cb4a85bc96cde4576fcdd3f200c6c66b
CandidateCDHashFull sha256=c5e445b7cb4a85bc96cde4576fcdd3f200c6c66bfad560176f4c1becb8c047f4
Hash choices=sha1,sha256
CMSDigest=4e0fe61d731f5db7fc0649fafd0b0316acfd78739b6e49c49f1b546cf6a73980
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=2932736
Executable Segment flags=0x0
Page size=4096
CDHash=c5e445b7cb4a85bc96cde4576fcdd3f200c6c66b
Signature size=9176
Authority=Developer ID Application: Institut fuer Elektronische Musik und Akustik der Kunstuniversitaet Graz (85W2432JR3)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=17 Jan 2024 at 22:32:07
Info.plist=not bound
TeamIdentifier=85W2432JR3
Sealed Resources=none
Internal requirements count=1 size=164

**Comment by Kendall555** [comment]
Also, I discovered something else. So if I first launch one of the help patches from the GEM folder Pd is able to create GEM objects and the patches that I created previously also work. And I'm also able to create new working patches too.

**Comment by umlaeute** [comment]
hah, i found something:
```
/Users/dovydasgataveckas/Documents/Pd/externals/Gem/Gem/Gem.pd_darwin
```

this path is wrong.
it really should read `/Users/dovydasgataveckas/Documents/Pd/externals/Gem/Gem.pd_darwin` (that's one less `Gem/` component in the path).

how did this come to pass?
the deken package only contains a single `Gem/` directory:

```sh
$ zipinfo "Gem[v0.94-snapshot](Darwin-amd64-32)(Darwin-arm64-32).dek"  | grep Gem.pd_darwin
-rwxr-xr-x  2.0 unx 11994272 b- defN 24-Jan-17 22:32 Gem/Gem.pd_darwin
$
```

and *normally*, deken will unpack the archive directly into `~/Documents/Pd/externals`.

so where does the double `Gem/` component come from?

**Comment by Kendall555** [comment]
I noticed that too. And to be honest, I have no clue where there did it come from. And what’s even weirder is that when I was deleting the library from the externals together with the double directory and was reinstalling it via Pd/Help/Find externals I would be prompted with an error message illustrated by the attached screenshot. So I assumed that that was normal? 
<img width="661" alt="Screenshot 2024-01-19 at 19 24 49" src="https://github.com/umlaeute/Gem/assets/156949381/5334a848-5d13-4521-bfc1-4be96b6b843b">

**Comment by umlaeute** [comment]
you can set the installation path for deken externals by
- opening deken
- in the *menu* go the <kbd>Edit</kbd> -> <kbd>Preferences...</kbd>
- in the preferences window you will see (among other things) a list of usual installation paths.
- select `/Users/dovydasgataveckas/Documents/Pd/externals/`
- apply the settings with <kbd>OK</kbd>

**Comment by Kendall555** [comment]
Ok, I went ahead and downloaded a fresh archive from deken.puredata.info/, unarchived it and placed the folder as a single directory in Externals. So far so good and patch files with Gem objects running normally regardless of them being in or out of the Gem folder. I'll update if I encounter any issues, hopefully I won't. Really looking forward to working with Gem, seems like  a really exciting tool, thank you for all of your help and work!

**Comment by Kendall555** [comment]
> you can set the installation path for deken externals by
> 
> * opening deken
> * in the _menu_ go the Edit -> Preferences...
> * in the preferences window you will see (among other things) a list of usual installation paths.
> * select `/Users/dovydasgataveckas/Documents/Pd/externals/`
> * apply the settings with OK

So, I'm not entirely sure but I think I've tried this and it was prompting me with the same error. If my current strategy mentioned in my previous comment doesn't work long term I'll give it a go!

**Comment by umlaeute** [comment]
>  If my current strategy

it seems like your "current strategy" is to download the file manually and then unarchive it.
in general i don't really like that approach (e.g. (as of today) using `deken` to install plugins bypasses the macOS gatekeeper unlike downloading files via Safari; the gatekeeper is one of those macOS thingies that might just go and make your downloaded binaries unusable; see also https://github.com/supercollider/supercollider/issues/6132#issuecomment-1880668463).

but anyhow: great that it works for you now.
i think we have established that the problem was not with Gem itself (nor it's packaging), so I'm closing this ticket.

**Comment by Kendall555** [comment]
Well, fair enough! I’ll keep that in mind and thank you for sharing that! 

Take care and all the best, Kendal
