### ISSUE TITLE
'film' plugin does not load

### ISSUE THREAD

**Issue by sp-photopic** [umlaeute/Gem#411]
Hi!

I try - and keep failing - to open a .mp4-file (or any other format for that matter) using `[pix_film]` (also tried to use `[pix_movie]`).

I use:
System: Fedora Linux 39 (Workstation)
pd:  0.54.1 64 bit (built from the current version on puredata.info)
gem: 0.94 (installed via deken)

I start pd via terminal. On startup i get the following:

> photopic@10:~$ pd
priority 94 scheduling failed.
open: /etc/pd/gem.conf: No such file or directory
open: /home/photopic/.config/pure-data/gem.conf: No such file or directory
open: ./gem.conf: No such file or directory
load plugins 'film' in '/home/photopic/Pd/externals/Gem/'
pattern : /home/photopic/Pd/externals/Gem/gem_film*.so
dylib loading file '/home/photopic/Pd/externals/Gem/gem_filmAVIPLAY.so'!
library loading returned: dlerror 'libaviplay-0.7.so.0: cannot open shared object file: No such file or directory'
dylib loading file '/home/photopic/Pd/externals/Gem/gem_filmGMERLIN.so'!
library loading returned: dlerror 'libgmerlin_avdec.so.1: cannot open shared object file: No such file or directory'
dylib loading file '/home/photopic/Pd/externals/Gem/gem_filmMPEG3.so'!
library loading returned: dlerror 'libmpeg3.so.2: cannot open shared object file: No such file or directory'
...

The complete output can be found here:
[photopic 10 pd.txt](https://github.com/umlaeute/Gem/files/14010893/photopic.10.pd.txt)

When I navigate to the Folder ...Pd/externals/Gem/ I can find all the .so-files it is looking for.

The pd-terminal gives me:
> WARNUNG: Zeichensatzfamilie 'DejaVu Sans Mono' nicht gefunden, Standard wird verwendet (courier)
GEM: Graphics Environment for Multimedia
GEM: ver: 0.94. 
GEM: compiled  on Jan 17 2024
GEM: maintained by IOhannes m zmoelnig
GEM: Authors :	Mark Danks (original version)
GEM:		Chris Clepper
GEM:		Cyrille Henry
GEM:		IOhannes m zmoelnig
GEM: with help by Guenter Geiger, Daniel Heckenberg, James Tittle, Hans-Christoph Steiner, et al.
GEM: found a bug? miss a feature? please report it:
GEM: 	homepage https://gem.iem.at/
GEM: 	bug-tracker https://bugs.gem.iem.at/
GEM: 	mailing-list https://lists.puredata.info/listinfo/gem-dev/
GEM: compiled for MMX/SSE2 architecture
GEM: using SSE2 optimization
GEM: detected 12 CPUs
GEM: image loading plugins: SGI STB jpeg tiff
GEM: image saving plugins: SGI STB jpeg tiff
GEM: model loading plugins: OBJ
GEM: video record plugins: PNM V4L V4L2
GEM: video capture plugins: NDI decklink v4l v4l2 vnc
priority 92 scheduling failed; running at normal priority

If I am not mistaken there should be something like "GEM: film loading plugins: ..."

Obviously, when I try to open a file via `[pix_film]` I get:

> [GEM:imageTIFF] /home/photopic/Pd/externals/Gem/examples/data/alea.mpg Not a TIFF or MDI file, bad magic number 0 (0x0)
[pix_film]: unable to open file: /home/photopic/Pd/externals/Gem/examples/data/alea.mpg

I tried to replace th .so-files with older versions i had on a backup. Still the film-plugin would not load :/

I'v been using pd and gem for more than ten years. Up to this point I always was able to solve problems by searching the forum but this time I seem to hit a brick wall :/ Can you help me with that issue?

**Comment by umlaeute** [comment]
this basically means that you do not have the (correct) libraries installed for film decoding.

when installing Gem via `deken`, a **README**-patch should have opened (unless you somehow disabled that in the deken-preferences) that told you:
> ### LINUX users
>
> please note that while we do provide downloadable pre-compiled binaries via deken, these do not include any dependencies, so are unlikely to run out-of-the box.
> instead, we suggest installing Gem via your distribution's package manager (which might install just enough dependencies to *also* get the snapshot to work).
>
> in general, we suggest to compile Gem yourself

Gem apparently shipped with 3 film plugins, that depend on the following libraries (that need to be provided by your system):
- `libaviplay-0.7.so.0` (i haven't used that one in ages, as it dropped out of Debian some time ago; dunno whether it still does anything useful)
- `libgmerlin_avdec.so.1` (this is what i typically use for playing video footage on Linux)
- `libmpeg3.so.2` (this is a very old library, that used to be able to decode mpeg2 files (iirc); probably not what you are looking for)

**Comment by sp-photopic** [comment]
Thank you for your quick response!

I will try that :)
