### ISSUE TITLE
Force rendering on gemhead not working 

### ISSUE THREAD

**Issue by Helli1995** [umlaeute/Gem#413]
### Detail

When sending a [bang( message to the gemhead, it is expected to send a rendering command to the chain, but it is not. Try in gemhead-helpfile.

### Gem Version

v0.94.git v0.94-843-gc6eff7f12

### Pd Version

0.52.2

### Operating System

macOS

### OS Version

13.5.1 (22G90) "Ventura"

### Which CPU are you using?

arm64 ("64bit ARM"; e.g. Apple Silicon,...)

**Comment by 60-hz** [comment]
It works here with Sonoma, same Gem version and pd-0.54-1

**Comment by umlaeute** [comment]
i'm also unsure whether i understand the problem.

in double-buffer mode (the default):
1. the drawing actually happens to an off-screen buffer, that is only swapped onto the window when the `[gemwin]` triggers
   - so whatever you are drawing is not immediately visible
2. the `[gemwin]` triggers a *clear buffer* first
   - so whatever you have drawn into the off-screen buffer with force-rendering is cleared

the help-patch doesn't really show (nor explain) this.
it also renders the all three geos anyhow (except for the `[square]`, which can be turned off), so forcing a rendering of the `[circle]` wouldn't really look different.
however, if you watch the PdConsole, you should see that when banging the `[gemhead]`, you do get a `FORCEABLE: gemList` printout - at least if there's a an active GemWindow.

**Comment by Helli1995** [comment]
Sorry for the confusion, now i understand better the way it is working. I tried the things you mentioned, the are working fine. So there is not an issue anymore.
