### ISSUE TITLE
gemwin no longer accept argument for the X server to use

### ISSUE THREAD

**Issue by ch-nry** [umlaeute/Gem#426]
### Detail

When using pd/Gem via ssh -X, [create :0< was forcing Gem to use local screen, better than the X forwarded screen.
Even if this was not officially advertised, this was very useful to debug/configure installation.
It no longer work, at least with gemglfw3window

### Gem Version

current git

### Operating System

Linux

### OS Version

ubuntu mate 22.04

### Which CPU are you using?

amd64/x86_64 ("64bit Intel")

**Comment by umlaeute** [comment]
indeed (i think; i haven't checked :-))

i did a quick check in the glfw docs, but i wasn't able to find a way to select the X-server :-/

**Comment by ch-nry** [comment]
that's alarming,
Do you know an other solution to have pd GUI on a computer and the patch/gemwindows on an other computer?

**Comment by umlaeute** [comment]
how about using `[gemglxwindow]` as the backend?

**Comment by ch-nry** [comment]
I switch to gemglfw3window according to this discussion : https://github.com/umlaeute/Gem/issues/406
I no longer know what I should use!

**Comment by umlaeute** [comment]
all right, we should figure this out :-)

- `[gemglfw3window]` is a good default choice, as it is available on all major platforms and provides a consistent interface to the Gem window. the price for the consistency is that some features of more specific backends cannot be used.

- after digging the source code of glfw, i am pretty sure that it is not possible to switch the X Display after glfw has been initialized (which is done when creating the first instance of `[gemglfw3window]`; more importantly, glfw can only be initialized once!).

   this basically rules out glfw as the backend if you want to open a window on a different display.
   (short of opening a feature request on https://github.com/glfw/glfw/; but I have no idea how long it would take for this to get implemented)

- so afaict the only backend that suits your needs (to open a window on a remote display), is `[gemglxwindow]`
  which means, that we need to unbreak it.

   #406 is a bit vague (and frankly, I forgot the off-tracker context), so it's hard to tell how to fix it. otoh, #406 was closed by me with a commit that supposedly fixed it, so maybe it is already unbroken?

**Comment by ch-nry** [comment]
Thanks,
The rendering was black. It is now fixed. So I switch back to gemglxwindow.
I'll create new and better bug report if I notice problem in gemglxwindow.
