### ISSUE TITLE
FSAA message did not work with gemglxwindow

### ISSUE THREAD

**Issue by ch-nry** [umlaeute/Gem#428]
### Detail

Sending a [FSAA 8<  message enable anti-aliasing when using gemglfw3window, but not when using the gemglxwindow.

### Gem Version

current git

### Operating System

Linux

### OS Version

ubuntu MATE 22.04

### Which CPU are you using?

amd64/x86_64 ("64bit Intel")

**Comment by umlaeute** [comment]
i don't think this ever worked in `[gemglxinfo]` (or rather: it always depended on nVidia-drivers honouring the `__GL_FSAA_MODE` envvar).

i've no changed it to mimick the behaviour of `[gemglfw3window]`.

**Comment by ch-nry** [comment]
it works here, with an intel GPU (linux)
thx

**Comment by umlaeute** [comment]
i have no idea why your `master` branch (b6c741145d4b46f51f95ff9dac19de825126d799) has diverged from mine (bc69202956ab2a3c6fd2249e2a6e9dfd487c0f17)
