### ISSUE TITLE
[GEM:videoNDI] [GEM:recordNDI] - libndi.4.dylib

### ISSUE THREAD

**Issue by giulianobici** [umlaeute/Gem#432]
### Detail

Hi 
I am teaching Gem at my classes and having problems to fix this issue

[GEM:recordNDI] Please (re)install the NewTek NDI Runtimes to use this plugin.
               need to find the library 'libndi.4.dylib'
               get it from http://new.tk/NDIRedistV4Apple
GEM: video record plugins: PNM
[GEM:videoNDI] Please (re)install the NewTek NDI Runtimes to use this plugin.
               need to find the library 'libndi.4.dylib'
               get it from http://new.tk/NDIRedistV4Apple
GEM: video capture plugins: AVF NDI decklink

best

### Gem Version

GEM: ver: 0.94.git v0.94-667-gc567ba77

### Pd Version

0.55-0

### Operating System

macOS

### OS Version

Ventura 13.6.7  

### Which CPU are you using?

amd64/x86_64 ("64bit Intel"), arm64 ("64bit ARM"; e.g. Apple Silicon,...), other

**Comment by giulianobici** [comment]
Here is the another message showed up too

[GEM:recordPNM] unknown extension: encoding will be PPM

best

**Comment by umlaeute** [comment]
So what is the problem?

The NDI message tells you that you won't be able to use NDI unless you install the relevant drivers (which it seems you haven't done) 
If you don't want to use NDI, there's no need to install the drivers.

**Comment by umlaeute** [comment]
The recordPNM warning is totally unrelated (aka: please don't use the same ticket to lump together unrelated stuff; I close tickets once the main issue is fixed, which means that the other stuff will get close even if unfixed).

Anyhow the warning tells you that you are trying to record to a file with an unexpected file extension. 
Eg recordPNM can *only* reform pnm sequences, it cannot eg record .mov files.

There are various recording plugins available and green tries to find a "best match", but sometimes it cannot find a *good* match. 

So is you are trying to record movies but have no proper movie recording plugin installed, it will eventually falls back to one that might not do what you want ... Which is what you are seeing here.

**Comment by giulianobici** [comment]
Sorry I didn't formulate well my question 
I couldn't find how to install the NDI from the link http://new.tk/NDIRedistV4Apple informed by Gem's message
Still trying to fixed it. I found some drivers on https://ndi.video/tools/download/   but still no idea how to record it
If it's possible to solve this issue in another way it would be great too. 
tks for all
