### ISSUE TITLE
texture coordinate are not set for line and point rendering for sphere and sphere3d primitives

### ISSUE THREAD

**Issue by ch-nry** [umlaeute/Gem#435]
### Detail

when rendering a sphere in line or point mode, the colour of the line/points are all the same, and change according to the texture colour at coordinate (0,0).

### Gem Version

current git

### Pd Version

0.55

### Operating System

Linux

### OS Version

ubuntu 22.04

### Which CPU are you using?

amd64/x86_64 ("64bit Intel")

**Comment by umlaeute** [comment]
is this a regression, or has it always been like that?

**Comment by umlaeute** [comment]
i see that the problem is there with "Debian/1:0.94-8+b3", so obviously not a regression.

other complex shapes (e.g. `[torus]` do work correctly)

**Comment by ch-nry** [comment]
Most geos act normally.
I don't think that it's a regression, it probably have ever been like that : it's not something used very often.

**Comment by ch-nry** [comment]
thanks, for the very fast fix!
