### ISSUE TITLE
[gemkeyname] inactive in fullscreen?

### ISSUE THREAD

**Issue by jamshark70** [umlaeute/Gem#454]
### Detail

I added this to my Gem patch so that I could close fullscreen mode. Linux (Ubuntu Studio 22.04), with xxf86vm-dev (Gem sources recognize it and build with it). `$0-toGemwin` turns 0 into "0, destroy".

![pd-close-gem](https://github.com/user-attachments/assets/6721724c-5a0b-47d9-8d36-68db08e488ac)

If the window is not fullscreen, focusing the Gem window and pressing Escape closes the window.

If the window is fullscreen, pressing Escape does nothing.

Had to force-reboot over this. Where to fix this?

### Gem Version

0.94.git v0.94-1028-g59e828732

### Pd Version

0.55.0

### Operating System

Linux

### OS Version

Ubuntu Studio 22.04

### Which CPU are you using?

amd64/x86_64 ("64bit Intel")

**Comment by umlaeute** [comment]
the behaviour actually depends on the windowing backend.
iirc, for some backends i just haven't managed to get keyboard events when in full-screen.

> Had to force-reboot over this. 

a better way is probably to just switch to the terminal (<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F1</kbd>), login, find the process-id of Pd/Gem and kill it. then switch back to the graphical session.

**Comment by jamshark70** [comment]
> should work now as of https://github.com/umlaeute/Gem/commit/c817127511340090168fb741957aa73bafa0c704

Confirmed! Thanks for the very quick fix.
