### ISSUE TITLE
pix_video crashing pd when selecting the wrong video device

### ISSUE THREAD

**Issue by jimruxton** [umlaeute/Gem#455]
### Detail

When I have my webcam running in a  Gem window using "device 0" , if I mistakenly hit "device 1" pd crashes. I figured I would get a warning or nothing happens but that it shouldn't crash pd. This happens using the SimpleVideo.pd example in the help browser for Gem. I have seen this happen as well with other device numbers when having external webcams or virtual cameras connected as well. I realize I shouldn't select a device that isn't there but it would be great if it didn't crash pd when I did. I also realize that when looking at v4l2-ctl --list-devices : It looks like there is a device 1 but there isn't. Maybe this has something to do with it crashing?
```
Integrated RGB Camera: Integrat (usb-0000:00:14.0-11):
	/dev/video0
	/dev/video1
	/dev/media0
```

### Gem Version

 ver: 0.94. "Debian/1:0.94-7"

### Pd Version

Pd 0.55.1

### Operating System

Linux

### OS Version

ubuntu 22.04 Jammy

### Which CPU are you using?

amd64/x86_64 ("64bit Intel")

**Comment by umlaeute** [comment]
Could you try again with a git snapshot build?

**Comment by jimruxton** [comment]
Thanks for your reply. I'll try that. I'm running a show with the current
version now but will test the new git version after the weekend to keep the
variables the same for now. Great to know there is an option to have the
crash not happen.

**Comment by jimruxton** [comment]
I tried installing a build from git but unfortunately this is causing a segmentation fault when I start PD. My console output follows.

jim@jim-Legion-7:~$ pd
open: /etc/pd/gem.conf: No such file or directory
open: /home/jim/.config/pure-data/gem.conf: No such file or directory
open: ./gem.conf: No such file or directory
load plugins 'film' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_film*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_filmFFMPEG.so'!
load plugins 'image' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_image*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageJPEG.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageSGI.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageSTB.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageTIFF.so'!
not reloading 'image' plugins (already 4 loaded)
load plugins 'image' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_image*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageJPEG.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageSGI.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageSTB.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageTIFF.so'!
load plugins 'model' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_model*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_modelASSIMP3.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_modelOBJ.so'!
load plugins 'record' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_record*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_recordDECKLINK.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_recordNDI.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_recordPIPEWIRE.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_recordPNM.so'!
load plugins 'video' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_video*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoDC1394.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoDECKLINK.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoNDI.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoPIPEWIRE.so'!
[W][08778.011611] spa.loop     | [          loop.c:  792 impl_clear()] 0x615f87618eb8: loop is entered 1 times
[E] pw.context [pipewire.c:256 load_spa_handle()] load lib: plugin directory undefined, set SPA_PLUGIN_DIR
[E] pw.loop [loop.c:86 pw_loop_new()] 0x615f87641080: can't make support.system handle: No such file or directory
Segmentation fault (core dumped)

**Comment by umlaeute** [comment]
luckily this can easily be fixed: just remove/rename the `gem_videoPIPEWIRE.so` file (when renaming, it's best to just change the extension, e.g. *gem_videoPIPEWIRE.so.disabled*)

**Comment by jimruxton** [comment]
I should probably also have included what Gem printed to my terminal. Its printed below.

jim@jim-Legion-7:~$ pd
open: /etc/pd/gem.conf: No such file or directory
open: /home/jim/.config/pure-data/gem.conf: No such file or directory
open: ./gem.conf: No such file or directory
load plugins 'film' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_film*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_filmFFMPEG.so'!
load plugins 'image' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_image*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageJPEG.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageSGI.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageSTB.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageTIFF.so'!
not reloading 'image' plugins (already 4 loaded)
load plugins 'image' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_image*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageJPEG.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageSGI.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageSTB.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_imageTIFF.so'!
load plugins 'model' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_model*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_modelASSIMP3.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_modelOBJ.so'!
load plugins 'record' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_record*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_recordDECKLINK.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_recordNDI.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_recordPIPEWIRE.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_recordPNM.so'!
load plugins 'video' in '/usr/local/lib/pd/extra/Gem/'
pattern : /usr/local/lib/pd/extra/Gem/gem_video*.so
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoDC1394.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoDECKLINK.so'!
dylib loading file '/usr/local/lib/pd/extra/Gem/gem_videoNDI.so'!
not reloading 'video' plugins (already 3 loaded)

**Comment by umlaeute** [comment]
it seems you compiled Gem yourself (rather than using the version from deken).
which is fine, but then you would need a couple of development files, in order to have support for this and for that :-)

most notably, for v4l2 support you need `libv4l-dev`
```sh
apt-get install libv4l-dev
```

then re-run `./configure && make && make install`

---

as a sidenote, it would be nice if you could put the console outputs into code-blocks:
`````
```
<log goes here>
```
`````

this way, i can better separate the output of Pd from your comments

**Comment by jimruxton** [comment]
Thank you. I will give this a try. I'm not using the Deken version because that version was crashing pd when I selected the wrong video device.

**Comment by umlaeute** [comment]
hmm, i thought your Debian Gem (`gem`) was crashing. the version you gave (`0.94. "Debian/1:0.94-7"`) indicates this.

**Comment by jimruxton** [comment]
Sorry I loaded it a while ago. I had assumed I got it from Deken where I get most of the externals. I guess I used apt. This new version from git works . It no longer crashes when trying to load a camera that doesn't exist. Thanks so much for the help.
