### ISSUE TITLE
filmDS : can't load anything after trying to load an unsupported file

### ISSUE THREAD

**Issue by avilleret** [umlaeute/Gem#63]
on Windows 7 with latest Gem from Git 

to reproduce : 
1. open `pix_film-help.pd`
2. open a supported file such as `examples/data/homer.avi`
3. try to open an unsupported file such as `examples/data/anim-1.mov`, you should see something like : `Unable to connect filters -2147220969` in red in the Pd's console.
4. try to  load `examples/data/homer.avi` again, and I got `Unable to add SampleFilter 262701`

**Comment by umlaeute** [comment]
i've marked this as "duplicate" as I grouped it together (with similar issues) into #180, but leave it open until it is really resolved.

**Comment by umlaeute** [comment]
seems to be fixed with the new `filmDS` implementation.
