### ISSUE TITLE
gemvertexbuffer crashes on Intel without multicontext on destroy()

### ISSUE THREAD

**Issue by avilleret** [umlaeute/Gem#87]
to reproduce : 
1. open gemvertexbuffer-help.pd
2. create a rendering window and start rendering.
3. stop rendering and close the window.
4. create a rendering window and start rendering again.
5. close the patch

Pd crashes with this backtrace : https://gist.github.com/avilleret/a958e735e6da1b435e5b

This happens on Intel driver (ubuntu 14.10) but Nvidia doesn't seems to be affected.

Maybe tomorrow this will be gone itself :-)

**Comment by umlaeute** [comment]
just checked back on the theory with context-sharing, and indeed: when i change the `context_sharing` variable in `gemglxwindow.cpp:674` to `false`, the crash goes away.
