### ISSUE TITLE
ImageMagick on Mac OS 10.10 library not found -lldtl

### ISSUE THREAD

**Issue by avilleret** [umlaeute/Gem#91]
here are the log : https://gist.github.com/avilleret/b04432e27e2967fd3f5c

ImageMagick have been installed through brew and I do have ltdl :

~~~~
$ ls -1 /usr/lib/libltdl.*
/usr/lib/libltdl.7.dylib
/usr/lib/libltdl.a
/usr/lib/libltdl.dylib
~~~~

what's wrong ?

**Comment by megrimm** [comment]
hey antoine,

have you tried this recently. i just tried on a fresh 10.10 install and did not have an issue compiling with imagemagick after just: $ brew install imagemagick

m

**Comment by avilleret** [comment]
hi,

I upgrade to imagemagick-6.9.0-9 but I'm still stuck here with this error.
btw I think it's more related to my installation rather than to Gem build system itself.

**Comment by umlaeute** [comment]
i think there are still some problems with libraries installed by `brew`, e.g. see #28.

so i think that these are problems outside of Gem's scope and will therefore close this ticket.
